### ISSUE TITLE
Documentation for Blackjack Guides: Style / Utilities

### ISSUE THREAD

**Issue by jackturnbull** [sky-uk/toolkit#102]
Bit of a drive-by but noticed that these don't appear anywhere in the wiki. Possibly expected to see these in the utilites section

**Comment by joebell93** [comment]
@jackturnbull finally going to pick this up!

Renaming to get into Blackjack Guides as well as the Wiki.

**Comment by joebell93** [comment]
**To do:**
~~_clearfix.scss~~ (Not really necessary to document in Guides)
~~_debug.scss~~ (Not finished, not worth documenting)
~~_defence.scss~~ (Don't think we should advertise using this, only in the Wiki) 

- [ ] _hide.scss

~~_ie9.scss~~ (This is already documented in installation)

- [ ] _spacing.scss
- [ ] _typography.scss
- [ ] _vertical-align.scss	
- [ ] _widths.scss

---

**Comment by MrDinsdale** [comment]
:shipit:

**Comment by StefanMcCready** [comment]
:shipit:

**Comment by joebell93** [comment]
@MrDinsdale @StefanMcCready cheers fellas

**Comment by joebell93** [comment]
@sky-uk/toolkit

I've added content to Sky Pages:
https://github.com/sky-uk/sky-pages/pull/1914
https://github.com/sky-uk/polaris-page-producer/pull/665

and it looks like this:
![screencapture-local-sky-3000-blackjack-toolkit-style-utilties-1476350525278](https://cloud.githubusercontent.com/assets/7349341/19344156/fe723a78-9130-11e6-9f7d-324b3143448a.png)

One this has merged I'll close the issue and add to the Wiki

**Comment by joebell93** [comment]
Added to https://github.com/sky-uk/toolkit/wiki/Toolkit-Core-Utilities
