### ISSUE TITLE
Provide documentation in Blackjack Guides

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit#103]
Here's the content we need for Blackjack Guides:

- [x] Introduction - first edit by @danieljbryson 
- [x] Getting Started (Developer intro)
- Style
    - [x] Colours - in progress @joebell93
    - [x] Gradients - in progress @joebell93
    - [ ] Elements - in progress @joebell93
    - [x] Typography - **(Blocked by Responsive Typography)**
- [x] Layout - first edit by @joebell93
- Components
    - [ ] Accordion (Up for debate. Styles live here but we'd encourage use of the Blackjack component) 
    - [x] Buttons - first edit by @danieljbryson and @joebell93
    - [ ] Forms
    - [x] Hero - first edit by @MrDinsdale  
    - [ ] Keyline
    - [x] Panel - first edit by @skitson 
    - [x] Select - first edit by @skitson 
    - [ ] Shine
    - [x] Spinner - first edit by @welikeideas
    - [x] Tables - first edit by @skitson 
    - [x] Tiles - first edit by @MrDinsdale 
    - [ ] Tooltip
- [ ] Resources (Design assets)

---

Component documentation structure:

# Component name

Introduction paragraph - purpose, useage, value.

### Base Title
- Description - purpose and function
- Code snippet (make sure this is fully valid and accessible HTML)
(repeat as necessary)

### Modifier Title
- Description - purpose and usage
- Code snippet (make sure this is fully valid and accessible HTML)
(repeat as necessary)

### State Title
- Description - purpose and usage
- Code snippet (make sure this is fully valid and accessible HTML)
(repeat as necessary)

**Comment by StefanMcCready** [comment]
Will pick up forms

**Comment by skitson** [comment]
I'll start with panels

**Comment by joebell93** [comment]
I'm gonna tidy up the first edits, then I'll pick up Spinner

**Comment by welikeideas** [comment]
Spinner content:

# Spinner

A spinner component is used to indicate that content is loading and is particularly useful for dynamically loaded content displaying an animated circle graphic.

A spinner may be required when elements of a page are still loading, or following a user interaction whilst new content is loaded. 

Once the content has loaded the spinner fades and should be replaced by the loaded content.

## Base
### Indicator
Displays a single spinner component in the page.

```
<strong class='c-spinner' role='progressbar'>Loading…</strong>
```

### Overlay
Used in tiles and displays a spinner with an opaque background over the top of the content to be loaded.

```
<article class="c-tile">
	<div class="c-tile__content">
		<div class="c-spinner-overlay c-spinner-overlay--light">
			<strong class="c-spinner" role="progressbar">Loading…</strong>
		</div>
		<img src="https://www.sky.com/assets2/star-wars-hero.jpg" alt="Sample image"/>
	</div>
</article>
```

## Modifiers
### Small Spinner
```
<strong class='c-spinner c-spinner--small' role='progressbar'>Loading…</strong>
```

### Large Spinner
```
<strong class='c-spinner c-spinner--large' role='progressbar'>Loading…</strong>
```

### Dark Overlay Spinner
Displays an Overlay Spinner using a dark background with a lighter, inverted Spinner to contrast with the darker background.

```
<article class="c-tile">
	<div class="c-tile__content">
		<div class="c-spinner-overlay c-spinner-overlay--dark">
			<strong class="c-spinner c-spinner--inverse" role="progressbar">Loading…</strong>
		</div>
		<img src="https://www.sky.com/assets2/star-wars-hero.jpg" alt="Sample image"/>
	</div>
</article>
```

**Comment by skitson** [comment]
## Panel
A panel component is usually used alongside a tile component. When a tile has been clicked and has an `is-selected` class, the panel component opens.
Panels typically contain further information relating to the tile component that has triggered the panel.
Panels span 100% width of the viewport and appear to split the document horizontally at page level.
### Base
#### Default panel
This is the panel component in it's basic default form. The default panel has a white background with dark text. When a panel is visible, it also has a class of `is-open`.
You can put any content you like inside a panel. It is recommended that you nest the content inside a wrapper with a class of `o-container`.
`<article class="c-panel is-open">
	<div class="c-panel__content">
		<a class="c-panel__toggle" href="#">Close</a>
		<div class="o-container">
			<h2>This is a title</h2>
			<p>This is a paragraph. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos officiis atque ab esse eaque, facilis dolor. Culpa quidem officiis, ea. Debitis, delectus? Hic quam rem, accusamus officia libero quidem unde.</p>
		</div>
	</div>
</article>`
### Modifiers
#### Dark panel
A dark version of the panel with a black background and white text.
`<article class="c-panel c-panel--dark is-open">
	<div class="c-panel__content">
		<a class="c-panel__toggle" href="#">Close</a>
		<div class="o-container">
			<h2>This is a title</h2>
			<p>This is a paragraph. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos officiis atque ab esse eaque, facilis dolor. Culpa quidem officiis, ea. Debitis, delectus? Hic quam rem, accusamus officia libero quidem unde.</p>
		</div>
	</div>
</article>`

**Comment by skitson** [comment]
## Tables
Tables are used to present tabular information. HTML table tags `<table>, <tbody>, <tr>, <td>` must be used in order to present information as a table. The default Toolkit table is borderless.

### Base
#### Default table
A default table has no toolkit classes attached to any of the table HTML tags. There are default styles applied directly to the table HTML tags.

```
<table>
	<tbody>
		<tr>
			<td>Content goes here</td>
			<td>Content goes here</td>
		</tr>
		<tr>
			<td>Content goes here</td>
			<td>Content goes here</td>
		</tr>
		<tr>
			<td>Content goes here</td>
			<td>Content goes here</td>
		</tr>
		<tr>
			<td>Content goes here</td>
			<td>Content goes here</td>
		</tr>
	</tbody>
</table>
```

### Modifiers
#### Simple table
A simple table adds dividing lines between table rows and has padding applied to each table cell allowing definition between cell content.

```
<table class="c-table-simple">
	<tbody>
		<tr class="c-table-simple__row">
			<td class="c-table-simple__cell">Content goes here</td>
			<td class="c-table-simple__cell">Content goes here</td>
		</tr>
		<tr class="c-table-simple__row">
			<td class="c-table-simple__cell">Content goes here</td>
			<td class="c-table-simple__cell">Content goes here</td>
		</tr>
		<tr class="c-table-simple__row">
			<td class="c-table-simple__cell">Content goes here</td>
			<td class="c-table-simple__cell">Content goes here</td>
		</tr>
		<tr class="c-table-simple__row">
			<td class="c-table-simple__cell">Content goes here</td>
			<td class="c-table-simple__cell">Content goes here</td>
		</tr>
	</tbody>
</table>
```

#### Borderless table
A bordrless table has no dividing lines between rows. This table has is no padding between cells.

```
<table class="o-table-borderless">
	<tbody>
		<tr>
			<td>Content goes here</td>
			<td>Content goes here</td>
		</tr>
		<tr>
			<td>Content goes here</td>
			<td>Content goes here</td>
		</tr>
		<tr>
			<td>Content goes here</td>
			<td>Content goes here</td>
		</tr>
		<tr>
			<td>Content goes here</td>
			<td>Content goes here</td>
		</tr>
	</tbody>
</table>
```

**Comment by skitson** [comment]
I've had a quick go at the Select guide. It doesn't include the radio button option and I'm pretty sure it could do with an edit or two but it's a start...

## Select
The select component can be used as a button with an on / off state toggled through user interaction - primarily a click event. The state of the button provides visual feedback relating to whether the button is selected or not.

### Base
#### Default select
The default select component has a transparent background with a blue border and blue text. On hover, the select component displays a white tick icon on a blue background to the right of the text. Clicking the select component will result in the checkbox input's state changing to checked causing the white tick icon (the same as displayed on hover) to display. Clicking the select component again will result in the checkbox input's state becoming unchecked, hiding the tick icon again (unless the hover state is currently activated).

```
<label class="c-select">
	<input type="checkbox" class="c-select__input">
	<span class="c-btn  c-btn--select  c-select__btn">Select</span>
</label>
```

### Modifiers
#### Is selected
By adding `is-selected` to the `<input type="checkbox">` element, the tick icon becomes a cross icon. This modifier is used when interaction with the select component signifies cancellation of an option where the default unchecked state of the checkbox input represents a selected option.

```
<label class="c-select">
	<input type="checkbox" class="c-select__input is-selected">
	<span class="c-btn  c-btn--select  c-select__btn">Select</span>
</label>
```

**Comment by joebell93** [comment]
Cheers everyone! I've updated the checklist, could do with a few more please 😄
