### ISSUE TITLE
Provide release documentation

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit#108]
- Document how core maintainers should release to GitHub and NPM

**Comment by MrDinsdale** [comment]
## Versioning

Toolkit follows semantic versioning, this allows us to communicate easily what impact a new version might have on project. Our release numbers follow the format:

`x.y.z`

- *x* MAJOR version indicating breaking changes and deprecations
- *y* MINOR version indicating new features but backwards compatibility with previous versions
- *z* PATCH version indicating backwards-compatible bug fixes

For example a user with `v1.0.0` knows they can safely update their project to `v1.0.1` or `v1.1.0` however upgrading to `v2.0.0` will most likely require updates to the project.

**Comment by joebell93** [comment]
Ah this was more about documenting the release process, rather than versioning
