### ISSUE TITLE
Documentation for Blackjack Guides: Components / Forms

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit#111]
Should follow the structure below:

---

# Component name

Introduction paragraph - purpose, useage, value.

### Base Title
- Description - purpose and function
- Code snippet (make sure this is fully valid and accessible HTML)
(repeat as necessary)

### Modifier Title
- Description - purpose and usage
- Code snippet (make sure this is fully valid and accessible HTML)
(repeat as necessary)

### State Title
- Description - purpose and usage
- Code snippet (make sure this is fully valid and accessible HTML)
(repeat as necessary)

**Comment by StefanMcCready** [comment]
[Forms.pdf](https://github.com/sky-uk/toolkit/files/449611/Forms.pdf)

Here is the content for forms, use as you please

**Comment by MrDinsdale** [comment]
@StefanMcCready Thanks! much appreciated

**Comment by joebell93** [comment]
Using some of what's been done already

---

# Forms

Forms are the standard way of receiving user inputted data, and therefore are an integral and crucial aspect of our interaction with customers. 

The Toolkit provides a range of accessible user input fields for different scenarios and data requirements.

If you're using React.js in your project, you may want to consider using [blackjack-forms](https://github.com/sky-uk/blackjack-forms).

## Base
### Form List
- Why list?
- Code snippet (make sure this is fully valid and accessible HTML)
(repeat as necessary)
 
### Text
- Text and email
- Code snippet (make sure this is fully valid and accessible HTML)
(repeat as necessary)

### Textarea
- Text and email
- Code snippet (make sure this is fully valid and accessible HTML)
(repeat as necessary)

### Combo
- Text and email
- Code snippet (make sure this is fully valid and accessible HTML)
(repeat as necessary)

### Select
- Description - purpose and function
- Code snippet (make sure this is fully valid and accessible HTML)
(repeat as necessary)

### Date Picker
- Description - purpose and function
- Code snippet (make sure this is fully valid and accessible HTML)
(repeat as necessary)

### Checkbox
- Description - purpose and function
- Code snippet (make sure this is fully valid and accessible HTML)
(repeat as necessary)

### Radio Buttons
- Description - purpose and function
- Code snippet (make sure this is fully valid and accessible HTML)
(repeat as necessary)

## Modifiers (if present/necessary)
### Modifier Title
- Description - purpose and usage
- Code snippet (make sure this is fully valid and accessible HTML)
(repeat as necessary)

## States (if present/necessary)
### State Title
- Description - purpose and usage
- Code snippet (make sure this is fully valid and accessible HTML)
(repeat as necessary)

**Comment by joebell93** [comment]
Seeing as this has had good verbal feedback I'm going to switch this to `ready`

**Comment by joebell93** [comment]
@sky-uk/toolkit

I've added content to Sky Pages and the Wiki:
https://github.com/sky-uk/sky-pages/pull/1914
https://github.com/sky-uk/polaris-page-producer/pull/665

and it looks like this:
![screencapture-local-sky-3000-blackjack-toolkit-components-divider-1476354094435](https://cloud.githubusercontent.com/assets/7349341/19345664/48ba1988-9137-11e6-9c7b-39cec61b349b.png)

**One this has merged I'll add to the Wiki**

**Comment by joebell93** [comment]
Added to Wiki
