### ISSUE TITLE
Documentation for Blackjack Guides: Components / Divider

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit#112]
Should follow the structure below:

---

# Component name

Introduction paragraph - purpose, useage, value.

### Base Title
- Description - purpose and function
- Code snippet (make sure this is fully valid and accessible HTML)
(repeat as necessary)

### Modifier Title
- Description - purpose and usage
- Code snippet (make sure this is fully valid and accessible HTML)
(repeat as necessary)

### State Title
- Description - purpose and usage
- Code snippet (make sure this is fully valid and accessible HTML)
(repeat as necessary)

**Comment by StefanMcCready** [comment]
[Keyline.pdf](https://github.com/sky-uk/toolkit/files/449823/Keyline.pdf)

**Comment by MrDinsdale** [comment]
@StefanMcCready Again this is fantastic

**Comment by joebell93** [comment]
# Divider

Dividers are used to dictate a thematic break in content or a shift in topic.

The Toolkit provides two components to create horizontal rules; `c-divider` for prominent breaks in content, and `c-keyline` for simple border boundaries.

## Base
### Divider
The divider in its basic form uses a gradient keyline and provides a prominent shadow on the bottom edge. By utilising `<hr>` we can easily place content above and below without disrupting the flow of the document.
```
<hr class="c-divider" />
```

### Keyline
The base keyline consists of a simple border, used for smaller subtle breaks in content.
```
<hr class="c-keyline" />
```

## Modifiers
### Top
Provides a horizontal divider with a prominent shadow on the top edge.
```
<hr class="c-divider  c-divider--top" />
```

## Utilities
Extra spacing can be applied on any edge with the [spacing utility](link-to-utilities) classes.

**Comment by joebell93** [comment]
@sky-uk/toolkit any thoughts on this?

**Comment by MrDinsdale** [comment]
Sounds good to me :shipit:

**Comment by joebell93** [comment]
@sky-uk/toolkit

I've added content to Sky Pages and the Wiki:
https://github.com/sky-uk/sky-pages/pull/1914
https://github.com/sky-uk/polaris-page-producer/pull/665

and it looks like this:
![screencapture-local-sky-3000-blackjack-toolkit-components-divider-1476354094435](https://cloud.githubusercontent.com/assets/7349341/19345664/48ba1988-9137-11e6-9c7b-39cec61b349b.png)

**One this has merged I'll add to the Wiki**

**Comment by joebell93** [comment]
Added to wiki
