### ISSUE TITLE
Are you really meant to be a public repository?

### ISSUE THREAD

**Issue by oliverlockwood** [sky-uk/toolkit#116]
We have noticed this repository was marked as public.  There are certain standards required before a repository in the `sky-uk` org can be made public, including the presence of valid `LICENSE.md`, `README.md`, and `CONTRIBUTING.md` files.
-  Repos without license information are immediately made private.
-  Repos failing the other criteria will be made private after 30 days.

Please resolve these problems ASAP and close this GitHub issue when you have done so.

If you have any questions, please ask them on the #github Slack channel.

**Comment by joebell93** [comment]
Thanks @oliverlockwood, this will be resolved tomorrow as we fully intend for this repo to be kept public.

**Comment by joebell93** [comment]
Closing this issue as we now have a License:
https://github.com/sky-uk/toolkit/blob/master/LICENSE
