### ISSUE TITLE
Bottom padding on select boxes is too small

### ISSUE THREAD

**Issue by StefanMcCready** [sky-uk/toolkit#118]
Toolkit UI Version: 5.0

Problem: There is a lack of padding at the bottom of the select box. This means that the select box looks very top heavy.

Has been noticed on the actual toolkit page and has been seen on Sky Mobile applications.

Screenshot: 

<img width="369" alt="screen shot 2016-09-20 at 13 04 38" src="https://cloud.githubusercontent.com/assets/14904083/18671753/376420c2-7f3d-11e6-8673-0545f7b8298c.png">

Browser:

Happens in all browsers

**Comment by joebell93** [comment]
Could you provide some more context to this and utilise the issue template?

We could do with some more details because it looks fine for me
