### ISSUE TITLE
Documentation for Blackjack Guides: Components / Dropdown

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit#120]
Added to:
- [ ] Blackjack Guides
- [ ] Wiki

---

# Dropdown Menu

Dropdown Menus provide a list of options or actions, with one choice per line, that affect the navigation or the current view.

The toggle label should provide appropriate context to reflect the contents of the menu, with each menu item clearly and concisely describing its action.

**Note:** Dropdown Menus **should not** be used in forms, instead use `c-form-select`.

### Dropdown

This is the Dropdown Menu component in its basic default form. In this scenario, a `<button>` is used to trigger a script for toggling the `.is-open` state to display and hide menu items.`aria-expanded="false"` should also be toggled to `true` when open to ensure full accessibility.
Menu items are stored as a list of links.

```
<div class="c-dropdown">
  <button id="dropdown1"
          class="c-dropdown__toggle"
          aria-haspopup="true"
          aria-expanded="false">
    Dropdown Menu
  </button>
  <ul class="c-dropdown__list"
      aria-labelledby="dropdown1">
    <li class="c-dropdown__item">
      <a href="#" class="c-dropdown__link">Menu item 1</a>
    </li>
    <li class="c-dropdown__item">
      <a href="#" class="c-dropdown__link">Menu item 2</a>
    </li>
    <li class="c-dropdown__item">
      <a href="#" class="c-dropdown__link">Menu item 3</a>
    </li>
    <li class="c-dropdown__item">
      <a href="#" class="c-dropdown__link">Menu item 4</a>
    </li>
  </ul>
</div>
```

### Open
- Toggling `.is-open` on `c-dropdown` allows us to hide/show menu items within the dropdown.
- `.is-open`

### Full Width
- For dropdowns that need to display full-width
- `.c-dropdown--full`

### Full Width (Small Only)
- For dropdowns that need to display full-width on small devices only
- `.c-dropdown--full@small-only`

**Comment by joebell93** [comment]
(First Draft)

---

# Dropdown Menu

Dropdown Menus provide a list of options or actions, with one choice per line, that affect the navigation or the current view.

The toggle label should provide appropriate context to reflect the contents of the menu, with each menu item clearly and concisely describing its action.

**Note:** Dropdown Menus **should not** be used in forms, instead use `c-form-select`.

## Base
### Dropdown

This is the Dropdown Menu component in its basic default form. In this scenario, a `<button>` is used to trigger a script for toggling the `.is-open` state to display and hide menu items. 

```
<div class="c-dropdown">
  <button id="dropdown1"
          class="c-dropdown__toggle"
          aria-haspopup="true"
          aria-expanded="false">
    Dropdown Menu
  </button>
  <ul class="c-dropdown__list"
      aria-labelledby="dropdown1">
    <li class="c-dropdown__item">
      <a href="#" class="c-dropdown__link">Menu item 1</a>
    </li>
    <li class="c-dropdown__item">
      <a href="#" class="c-dropdown__link">Menu item 2</a>
    </li>
    <li class="c-dropdown__item">
      <a href="#" class="c-dropdown__link">Menu item 3</a>
    </li>
    <li class="c-dropdown__item">
      <a href="#" class="c-dropdown__link">Menu item 4</a>
    </li>
  </ul>
</div>
```

## Modifiers (if present/necessary)
### Modifier Title
- Description - purpose and usage
- Code snippet (make sure this is fully valid and accessible HTML)
(repeat as necessary)

## States (if present/necessary)
### State Title
- Description - purpose and usage
- Code snippet (make sure this is fully valid and accessible HTML)
(repeat as necessary)

**Comment by joebell93** [comment]
@sky-uk/toolkit please can I get a review on this?

**Comment by skitson** [comment]
LGTM - only thing I would do would be consider separating the full width modifiers to make it crystal clear:

- For dropdowns that need to display full width always `.c-dropdown--full`

- For dropdowns that only display full width on small devices `.c-dropdown--full\@small-only`

👍 👍 👍

**Comment by joebell93** [comment]
@skitson sounds good to me, will amend this now!

**Comment by joebell93** [comment]
Add to:
- [ ] Blackjack Guides
- [ ] Wiki

**Comment by joebell93** [comment]
@sky-uk/toolkit

I've added content to Sky Pages and the Wiki:
https://github.com/sky-uk/sky-pages/pull/1914
https://github.com/sky-uk/polaris-page-producer/pull/665

**Note**: This CSS is in `1.0` and therefore not visible yet

and it looks like this:
![screencapture-local-sky-3000-blackjack-toolkit-components-dropdown-1476433859353](https://cloud.githubusercontent.com/assets/7349341/19380916/53155518-91f1-11e6-9b17-e77088a83dc5.png)

**One this has merged I'll add to the Wiki**

**Comment by joebell93** [comment]
Added to https://github.com/sky-uk/toolkit/wiki/Toolkit-UI-Dropdown
