### ISSUE TITLE
Building and deploying the CSS file

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit#125]
We need to deploy a CSS file for use on GitHub pages, prototypes and many other scenarios.
- Where should it live? -`sky.com/assets/toolkit/v1/toolkit.css`
- How should we deploy it?

Discussing with @lbarratt tomorrow

**Comment by joebell93** [comment]
Created a `dist` function in https://github.com/sky-uk/toolkit/pull/126

@lbarratt to investigate a deployment mechanism on Friday 💃

**Comment by MrDinsdale** [comment]
Update from @lbarratt:

Still need to look at the automated release upload for the compiled toolkit code

the process is something like:
- Write a shell script to run `npm run dist` and push the `.css` to s3
- Update `circle.yml` to run the script on every build with a tagged release version

**Comment by joebell93** [comment]
I've done some investigation on this, think it's best to hold off until we have a monorepo

cc/ @lbarratt

**Comment by joebell93** [comment]
Some commits previously referenced to this Issue:
https://github.com/sky-uk/toolkit/issues/225

**Comment by joebell93** [comment]
Released in https://github.com/sky-uk/toolkit/pull/396
