### ISSUE TITLE
Documentation for Blackjack Guides: Components / Tile

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit#128]
Update to include the `--full` tile and `.has-focus` state

**Comment by MrDinsdale** [comment]
# toolkit-ui / tile

## Contents

0. [Overview](#overview)
0. [Installation](#installation)
0. [Base](#base)
0. [Modifiers](#modifiers)
0. [States](#states)

## Overview

Tiles are made of a glass edge with a shine on hover, they contain our content and allow any colour beneath to show though.

Tiles open panels or link to new pages.

*Note: Do not feel that all your content must fit within a tile and panel format.*

### Installation
For in-depth instructions follow the guide on [how to get started with Toolkit](https://github.com/sky-uk/toolkit/wiki/Getting-started) in your project.

#### Dependencies

``` css
sky-toolkit-core/all
sky-toolkit-ui/components/tile
sky-toolkit-ui/components/shine
```

## Base

### Standard Tile

This is the Tile component in its most simple form.

``` html
<article class="c-tile">
  <div class="c-tile__content">
    <div class="c-tile__body">
      <p class="c-heading-delta  u-margin-bottom-none">Tile Title</p>
      <p class="c-text-body">Tile Content</p>
    </div>
  </div>
</article>
```

### Split Media Tile

The split media tile allows for an image to be placed in the top half of the tile and title to be placed below.

``` html
<article class="c-tile  c-tile--square">
  <a class="c-tile__link" href="#">
    <div class="c-tile__content">
      <div class="c-tile__media">
        <img class="c-tile__poster" src="url-to-image" />
      </div>
      <div class="c-tile__body  c-tile__caption">
        <p class="c-heading-delta  u-margin-bottom-none">Tile Title</p>
      </div>
    </div>
  </a>
</article>
```

### Full Tile

The full tile allows for an image to be placed as a background for the tile and title to be placed at the bottom.

``` html
<article class="c-tile  c-tile--square  c-tile--full">
  <a class="c-tile__link" href="#">
    <div class="c-tile__content">
      <div class="c-tile__media">
        <img class="c-tile__poster" src="url-to-image" />
      </div>
      <div class="c-tile__body">
        <div class="c-tile__overlay">
          <p class="c-heading-delta  u-margin-bottom-none">Tile Title</p>
        </div>
      </div>
    </div>
  </a>
</article>
```

## Modifiers

### Square

The square modifier sets a fixed ratio for equal tile height and width. To remove this forced ratio on the **medium** breakpoint see `.c-tile--collapsable` in modifiers.

*Please note that square tiles can cause issues with scaling typography.*

``` html
<article class="c-tile  c-tile--square">
  <div class="c-tile__content">
    <div class="c-tile__body">
      <p class="c-heading-delta  u-margin-bottom-none">Tile Title</p>
      <p class="c-text-body">Tile Content</p>
    </div>
  </div>
</article>
```

### Collapsable

The collapsable tile is used in conjuncture with the `.c-tile--square` to remove the height constraint for mobile breakpoints and allow the tile to inherit height from its content. If used on a tile featuring the `.c-tile__media` element it will hide this image on mobile. This is useful for conserving space on small screens.

``` html
<article class="c-tile  c-tile--square  c-tile--collapsable">
  <a class="c-tile__link" href="#">
    <div class="c-tile__content">
      <div class="c-tile__media">
        <img class="c-tile__poster" src="url-to-image" />
      </div>
      <div class="c-tile__body  c-tile__caption">
        <p class="c-heading-delta  u-margin-bottom-none">Tile Title</p>
      </div>
    </div>
  </a>
</article>
```

### Channel themes

For split tiles requiring branded hover states simply include the name of the channel in the format of the gradient names defined in [toolkit-core/settings/colors](https://github.com/sky-uk/toolkit-core/blob/master/settings/_colors.scss) such as `.c-tile--sky-atlantic`.

``` html
<article class="c-tile  c-tile--square  c-tile--sky-atlantic">
  <a class="c-tile__link" href="#">
    <div class="c-tile__content">
      <div class="c-tile__media">
        <img class="c-tile__poster" src="url-to-image" />
      </div>
      <div class="c-tile__body  c-tile__caption">
        <p class="c-heading-delta  u-margin-bottom-none">Sky Atlantic</p>
      </div>
    </div>
  </a>
</article>
```

### Panel Themes

As the indicator arrow to show that the corresponding panel is open is part of the tile we can use the `.c-tile--dark` class to match the tile indicator to the panel.

``` html
<article class="c-tile  c-tile--dark">
  /* tile contents */
</article>
```

## States

### Focus

We can programmatically apply a has focus class to Tiles by adding the `.has-focus` state. This is a requirement for accessibility.

``` html
<article class="c-tile  has-focus">
  /* tile contents */
</article>
```

### Selected

The `.is-selected` class is used to signify that a tile is selected and its corresponding panel is open and display the indicator. It should only be used in combination with a panel.

``` html
<article class="c-tile  is-selected">
  /* tile contents */
</article>
```

**Comment by MrDinsdale** [comment]
So this has been updated (minus example images) and fits in line with the blackjack guides docs.

Are people happy with the depth? We don't really go in to any depth about the elements that are used to construct it such as `c-tile__content` etc.

**Comment by joebell93** [comment]
Yeah I think this is good @MrDinsdale, although it would be good to have some design perspective in the descriptions too. Maybe something we can ask Dan for?

**Comment by joebell93** [comment]
I've refactored the structure you did a bit @MrDinsdale before adding into the Guides - made sense to move the panel theme into the `is-selected` stuff:

---

# toolkit-ui / tile

## Contents

0. [Overview](#overview)
0. [Installation](#installation)
0. [Base](#base)
0. [Modifiers](#modifiers)
0. [States](#states)

## Overview

Tiles are made of a glass edge with a shine on hover, they contain our content and allow any colour beneath to show though.

Tiles open panels or link to new pages.

*Note: Do not feel that all your content must fit within a tile and panel format.*

### Installation
For in-depth instructions follow the guide on [how to get started with Toolkit](https://github.com/sky-uk/toolkit/wiki/Getting-started) in your project.

#### Dependencies

``` css
sky-toolkit-core/all
sky-toolkit-ui/components/tile
sky-toolkit-ui/components/shine
```

## Base

### Standard Tile

![screen shot 2016-10-11 at 16 35 14](https://cloud.githubusercontent.com/assets/2472440/19277217/e49312aa-8fd0-11e6-8df8-24d652f59b78.png)

This is the Tile component in its most simple form.

``` html
<article class="c-tile">
  <div class="c-tile__content">
    <div class="c-tile__body">
      <p class="c-heading-delta  u-margin-bottom-none">Tile Title</p>
      <p class="c-text-body">Tile Content</p>
    </div>
  </div>
</article>
```

### Split Media Tile

![screen shot 2016-10-11 at 16 35 29](https://cloud.githubusercontent.com/assets/2472440/19277229/ea851500-8fd0-11e6-9f03-d51e444302ef.png)

The split media tile allows for an image to be placed in the top half of the tile and title to be placed below.

``` html
<article class="c-tile  c-tile--square">
  <a class="c-tile__link" href="#">
    <div class="c-tile__content">
      <div class="c-tile__media">
        <img class="c-tile__poster" src="url-to-image" />
      </div>
      <div class="c-tile__body  c-tile__caption">
        <p class="c-heading-delta  u-margin-bottom-none">Tile Title</p>
      </div>
    </div>
  </a>
</article>
```

### Full Tile

The full tile allows for an image to be placed as a background for the tile and title to be placed at the bottom.

``` html
<article class="c-tile  c-tile--square  c-tile--full">
  <a class="c-tile__link" href="#">
    <div class="c-tile__content">
      <div class="c-tile__media">
        <img class="c-tile__poster" src="url-to-image" />
      </div>
      <div class="c-tile__body">
        <div class="c-tile__overlay">
          <p class="c-heading-delta  u-margin-bottom-none">Tile Title</p>
        </div>
      </div>
    </div>
  </a>
</article>
```

## Modifiers

### Square

![screen shot 2016-10-11 at 16 35 43](https://cloud.githubusercontent.com/assets/2472440/19277244/f4f23e78-8fd0-11e6-9bc9-5136069683df.png)

The square modifier sets a fixed ratio for equal tile height and width. To remove this forced ratio on the **medium** breakpoint see `.c-tile--collapsable` in modifiers.

*Please note that square tiles can cause issues with scaling typography.*

``` html
<article class="c-tile  c-tile--square">
  <div class="c-tile__content">
    <div class="c-tile__body">
      <p class="c-heading-delta  u-margin-bottom-none">Tile Title</p>
      <p class="c-text-body">Tile Content</p>
    </div>
  </div>
</article>
```

### Collapsable

The collapsable tile is used in conjuncture with the `.c-tile--square` to remove the height constraint for mobile breakpoints and allow the tile to inherit height from its content. If used on a tile featuring the `.c-tile__media` element it will hide this image on mobile. This is useful for conserving space on small screens.

``` html
<article class="c-tile  c-tile--square  c-tile--collapsable">
  <a class="c-tile__link" href="#">
    <div class="c-tile__content">
      <div class="c-tile__media">
        <img class="c-tile__poster" src="url-to-image" />
      </div>
      <div class="c-tile__body  c-tile__caption">
        <p class="c-heading-delta  u-margin-bottom-none">Tile Title</p>
      </div>
    </div>
  </a>
</article>
```

### Channel themes

![screen shot 2016-10-11 at 16 36 06](https://cloud.githubusercontent.com/assets/2472440/19277314/28f4833e-8fd1-11e6-8190-431ad8c30913.png)

For split tiles requiring branded hover states simply include the name of the channel in the format of the gradient names defined in [toolkit-core/settings/colors](https://github.com/sky-uk/toolkit-core/blob/master/settings/_colors.scss) such as `.c-tile--sky-atlantic`.

``` html
<article class="c-tile  c-tile--square  c-tile--sky-atlantic">
  <a class="c-tile__link" href="#">
    <div class="c-tile__content">
      <div class="c-tile__media">
        <img class="c-tile__poster" src="url-to-image" />
      </div>
      <div class="c-tile__body  c-tile__caption">
        <p class="c-heading-delta  u-margin-bottom-none">Sky Atlantic</p>
      </div>
    </div>
  </a>
</article>
```

## States

### Focus

We can programmatically apply a has focus class to Tiles by adding the `.has-focus` state. This is a requirement for accessibility.

``` html
<article class="c-tile  has-focus">
  /* tile contents */
</article>
```

### Selected

The `.is-selected` class is used to signify that a tile is selected and its corresponding panel is open and display the indicator. It should only be used in combination with a panel.

``` html
<article class="c-tile  is-selected">
  /* tile contents */
</article>
```

### Selected (Dark)

As the indicator arrow to show that the corresponding panel is open is part of the tile we can use the `.c-tile--dark` class to match the tile indicator to the panel.

``` html
<article class="c-tile  c-tile--dark">
  /* tile contents */
</article>
```

**Comment by joebell93** [comment]
@sky-uk/toolkit

I've added content to Sky Pages:
https://github.com/sky-uk/sky-pages/pull/1914
https://github.com/sky-uk/polaris-page-producer/pull/665

and it looks like this:
![tiles](https://cloud.githubusercontent.com/assets/7349341/19383268/57293d54-91fb-11e6-9f38-10db88b16883.jpg)

**One this has merged I'll add to the Wiki**

**Comment by joebell93** [comment]
Added to Wiki
