### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by paulgrav** [sky-uk/toolkit#132]
I think the README could do with stating what this project actually is. From what I’ve been able to deduce this project is not the actually toolkit itself but rather a Jekyll site that showcases the toolkit. If this is the case, then I think that information could do with going into the README.

To summarise I think it would useful to have the README state the following:

- Purpose. Intended audience? What does it do? What does it not do? Who is it not for?
- What is it? What technologies does it require? Looks like Ruby is a requirement but what version?

**Comment by joebell93** [comment]
Struggling to see how this isn't clear?

---

# Toolkit 

Sky's CSS Toolkit.

- [See the Wiki](https://github.com/sky-uk/toolkit/wiki/) for full documenation.
- [See the Style Guide](http://sky-uk.github.io/toolkit/) to view currently available Toolkit components.

**Note**: The Toolkit is still in active development and not yet 100% stable. This means breaking updates may occur, minor issues and quirks may be present.

## Goals

- Enable teams across tribes to share common styles.
- Provide a modular approach to handling CSS/Sass components.
- Provide example use cases with a generated style guide.

## Structure

The project consists of 3 repositories: 

- **this repo**: consumes the UI and Core layers and serves static pages.
- [toolkit-core](https://github.com/sky-uk/toolkit-core): Global styles and defaults for all projects.
- [toolkit-ui](https://github.com/sky-uk/toolkit-ui): Aesthetic components following Polaris brand guidelines.

**Comment by lbarratt** [comment]
Hey @paulgrav - are there any changes you could suggest specifically? I think a PR would be great here?

This repo contains a Jekyll site as a placeholder style guide, although this will eventually be removed. Currently it provides the `package.json` to pull `toolkit-core` and `toolkit-ui` into an npm project.

The package is listed on npm here: https://www.npmjs.com/package/sky-toolkit

**Comment by paulgrav** [comment]
I did read the README, thanks. Specifically, there’s no mention of Jekyll, there’s no mention of how to build or serve this project. There’s no mention of Jekyll’s dependencies.

I didn’t have perms to push a branch hence the lack of PR.

**Comment by lbarratt** [comment]
Cheers for the feedback @paulgrav.

Commits are restricted to core contributors on this repo directly - would you be okay to fork this?

**Comment by joebell93** [comment]
@paulgrav the style guide is available in the internal docs (link in Slack, we can't mention publicly)

Jekyll will be removed in `release/v1` and this repo will be solely for the Wiki (public docs) and serving a `package.json`

**Comment by paulgrav** [comment]
@joebell93 That’s great info that, IMO, would have been super useful to me in the README. 

The Jekyll stuff was actually useful because it allowed me to fire up the a toolkit based site with very little effort and better understand how it works.

**Comment by joebell93** [comment]
@paulgrav I'd recommend using [blackjack-toolbelt](https://github.com/sky-uk/blackjack-toolbelt) to spin up a quick playground with Toolkit styles.

Will add that to the `README.md` in `release/v1` and close for now (as release is imminent).
