### ISSUE TITLE
[Feature] Responsive Tables

### ISSUE THREAD

**Issue by oliverrushworthsky** [sky-uk/toolkit#139]
It would be useful to have the option to make tables responsive, we have recently implemented a feature like this in the Sky Forum: 

![image](https://cloud.githubusercontent.com/assets/13519940/19768169/4eabc072-9c4e-11e6-8ff1-3b449ef2d873.png)

This is increasing important as more of our customers are using mobile to access the site. we've had a quick look into different examples and found this article to be the best: 
https://css-tricks.com/accessible-simple-responsive-tables/

**Comment by joebell93** [comment]
We're currently blocked by design on this unfortunately 😢 

https://github.com/sky-uk/toolkit-ui/pull/116
