### ISSUE TITLE
[Docs] Layout - Expand grid examples and usage

### ISSUE THREAD

**Issue by MrDinsdale** [sky-uk/toolkit#147]
Expand example usage of the layout.

- [ ] The purpose of `o-layout` and `o-layout__item` along with their relationship.
- [ ] More examples of layouts inline with other frameworks like Foundation/Bootstrap.

**Comment by MrDinsdale** [comment]
https://github.com/sky-uk/polaris-page-producer/pull/789

**Comment by joebell93** [comment]
Reviewed

**Comment by MrDinsdale** [comment]
@joebell93 updated with changes
