### ISSUE TITLE
[Docs] Components / tile-fluid

### ISSUE THREAD

**Issue by MrDinsdale** [sky-uk/toolkit#153]
Add documentation for `c-tile--fluid` and associated classes.

**Comment by joebell93** [comment]
@mrdinsdale what's the status on this?

**Comment by joebell93** [comment]
@mrdinsdale what's the status on this?

**Comment by MrDinsdale** [comment]
This is almost ready. Just waiting on a bug fix which removes legacy fluid styling for Sky Pages. PRs:
SP https://github.com/sky-uk/sky-pages/pull/2596/
PPP https://github.com/sky-uk/polaris-page-producer/pull/970

**Comment by steveduffin** [comment]
Closing - to be replaced with a different solution
