### ISSUE TITLE
[accessibility] Panel close to use button element

### ISSUE THREAD

**Issue by MrDinsdale** [sky-uk/toolkit#159]
Currently we promote using `a` elements for panel close button. We should perhaps be using the `button` element for more semantic markup.

**Comment by joebell93** [comment]
Let's add to sky.com/toolkit

**Comment by MrDinsdale** [comment]
@joebell93 We need to probably update styling for this before promoting

**Comment by joebell93** [comment]
@MrDinsdale what do you mean?

**Comment by MrDinsdale** [comment]
Button elements have default styling (borders bg etc) which need removing first.

**Comment by joebell93** [comment]
So are you suggesting we have a button class that removes all normalised styling and replicates a link?

**Comment by joebell93** [comment]
Closing this due to https://github.com/sky-uk/toolkit/issues/177
