### ISSUE TITLE
[bug] Forms select box arrow not clickable (IE)

### ISSUE THREAD

**Issue by MrDinsdale** [sky-uk/toolkit#162]
## Expected Behavior
When using IE the user should be able to click anywhere in the form select box to interact.

## Current Behavior
If the user clicks the arrow the select box does not open

## Attempted Fixes
`pointer-events` is already set to `none` on the pseudo element containing the arrow. May need a spike to look at alternatives/prioritise this issue.

## Steps to Reproduce (for bugs)

0. Open page featuring Toolkit select box.
0. Click text, select box opens.
0. Click arrow, no interaction is registered despite pointer icon showing

## Context
This was spotted in Sky Mobile, issue is not too severe as the select box still functions when clicked elsewhere however could cause annoyance as the cursor indicates that it is clickable.

## Your Environment
* IE10, IE9
* Tested in Virtualbox in Windows7

**Comment by MrDinsdale** [comment]
Had a quick play with fixing this however didn't find a work around as all the obvious fixes for this are already in place.

**Comment by joebell93** [comment]
Looks like @geit might be onto this https://github.com/sky-uk/toolkit-ui/pull/206

**Comment by joebell93** [comment]
Fixed in https://github.com/sky-uk/toolkit-ui/pull/206
