### ISSUE TITLE
[Discussion] How we handle breakpoints in external components 

### ISSUE THREAD

**Issue by MrDinsdale** [sky-uk/toolkit#168]
There have been some concerns regarding how components such as Toolkit-React should handle responsive breakpoints.

Should components hardcode breakpoints? This would prevent issues cause by projects with non-toolkit breakpoints such as Sky Pages however this gets complicated when layouts and grids are introduced.

**Comment by joebell93** [comment]
This is why I personally believe we **shouldn't** encourage people to change these breakpoints

We need better consistency anyway

**Comment by aaronthomas** [comment]
Totally agree we shouldn't _change_ preset breakpoints that are already defined, but we should be free (and perhaps encouraged) to create component specific breakpoints that are unique and unrelated to sky-pages (or Toolkit) breakpoints.

Toolkit breakpoints were always meant to be a set of sensible defaults, not an exhaustive/restrictive list of breakpoints for every single component.

**Comment by MrDinsdale** [comment]
What about scenarios where we have a calendar for example, this is designed to be full width. A design calls for it to be used in a 1/2 or 2/3 column, the component has not context so will likely break.

In that scenario do we build additional functionality to handle this within the component or do we hand over control to the application?

One option would be to define component specific breakpoints such as:

``` scss
$calendar-breakpoints: (
    small: 420,
    medium: 720
) !default;
```

These would be hardcoded to suit the components design but capable of being overwritten if required.

**Comment by MrDinsdale** [comment]
PS I do mostly agree that we should have a set of core breakpoints we try and align to, the problem is we have a set of arbitrary values currently set.

If we are going to encourage people to use the default Toolkit values we should base them on existing projects.

**Comment by joebell93** [comment]
I'm going to close this until it pops up again as an issue

I can see component-specific breakpoints potentially becoming useful in the near future
