### ISSUE TITLE
Toolkit Steering 14th February 2017 Ideas

### ISSUE THREAD

**Issue by claredevine** [sky-uk/toolkit#170]
In preparation for the next steering meeting I would like to produce an agenda and also start to get the ball rolling on the possible addition of `UI` and `Core` into `toolkit`.

The main topic of discussion will be the `2.0` release.
What would you like to see in the release?
What aspects of the toolkit do you feel needs improvement?

Feel free to add any comments below, and I'll produce and distribute an agenda before the meeting.

**Comment by StefanMcCready** [comment]
My thoughts on Three in to One: 

It surprises me this isn't already the case, but I never really picked up on it until it was brought up. but it makes sense to go ahead with it. For me personally would make sense to have a structure of one package with a `CORE` and `UI` folder, however to allow for different UI Themes (content as an example) having two packages in one repo makes perfect sense in that regard. There is then also the question of a smooth transition for people using toolkit.

**Comment by StefanMcCready** [comment]
Would also be good to get updates on Typescale progress.. which I have been asked to create codepens for so could maybe show that at this meeting.

**Comment by joebell93** [comment]
Think we're some time off Typography yet

Spent some time with @mikegregory on this, you can see a spike for it here - https://stage-watch-pr-3082.herokuapp.com/

**Comment by MrDinsdale** [comment]
It would be good to start looking at some `toolkit-ui` brand layers (for want of a better term).

In `mobile-account` I have started building up a set of styling to add our mobile specific colours and gradients along with some mobile specific component such as disco toggles:
![screen shot 2017-02-10 at 14 28 40](https://cloud.githubusercontent.com/assets/2472440/22830123/412bf7c6-ef9d-11e6-83d2-e52ba19a36a8.png)

Currently it needs work and is restricted to Sky Pages for now. Would be interesting to see what peoples thoughts are on this and where it should live. I was contemplating a `toolkit-ui-mobile` repo perhaps although it would be good to get more feedback.

**Comment by gregorypratt** [comment]
@MrDinsdale do you mean how could the Toolkit support custom themes?

**Comment by MrDinsdale** [comment]
@gregorypratt Thats much more eloquently put. Yeah basically 😂

**Comment by StefanMcCready** [comment]
@MrDinsdale thats not a bad shout, would certainly help mobile as we have so many common themes

**Comment by aaronthomas** [comment]
@MrDinsdale Totally agree, as we have pretty much the same component:

![screen shot 2017-02-10 at 14 51 18](https://cloud.githubusercontent.com/assets/1419558/22830994/8c70bcdc-efa0-11e6-90cb-7fee9485214f.png)

They even used to have the disco border like yours, but that was changed by Design.

**Comment by claredevine** [comment]
What would we like to see in 2.0:

- Skycon buttons (Joe and Aaron currently in talks about this)

**Comment by claredevine** [comment]
We also need an actual meeting room for these meetings!

**Comment by lynasj** [comment]
I've requested Sky 1 0.2 for Wednesdays 3-3.30
