### ISSUE TITLE
[Enhancement] `z-index` strategies

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit#176]
Moved from https://github.com/sky-uk/toolkit-core/issues/53 to ease with **Toolkit 2.0** monorepo tracking

---

>It would be nice if we can avoid the dreaded `z-index: 99999999999999999999999999999999999999999;` problem on this project, so let’s look at either
>1. [Linting for sane values](https://github.com/brigade/scss-lint/issues/460) or…
>2. Managing our `z-index` values in a map or settings file.
>
>`z-index` will likely be more problematic when we’re working with UI, because Core’s stacking will probably be pretty concrete. This raises questions of if/how do we manage `z-index` across both Core and UI, and where to we allow consumers to change or update `z-index` in their specific circumstances?

– @csswizardry

**Comment by joebell93** [comment]
Made a stab at this already using @gregorypratt's suggestions in the previous issue:

- https://github.com/sky-uk/toolkit-core/pull/157
- https://github.com/sky-uk/toolkit-ui/pull/196

**Comment by csswizardry** [comment]
**IDEA:** Discussed with @joebell93, @jwalton9, and @lbarratt: general feeling is that this may well work.

Instead of having a map like:

```
$z-index: (
  'over-content': 100,
  'under-content': 50,
);
```

…which is very tied to design, why not just have:

```
$z-index: (
  0: 0,
  1: 10,
  2: 20,
  ...
  10: 100
);
```

This:

* completely divorced from whatever our design may be;
* allows people to nudge things around (a little higher, a little lower…);
* keeps things within known bounds/constraints.

**Comment by csswizardry** [comment]
Commits here: https://github.com/sky-uk/toolkit-core/compare/release/v2...tkt-00176

**Comment by joebell93** [comment]
I like this better, I think the previous concept of naming our `z-index` values could cause more confusion than necessary
