### ISSUE TITLE
[Feature] Faux Links

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit#177]
Moved from https://github.com/sky-uk/toolkit-ui/issues/209 to ease with **Toolkit 2.0** monorepo tracking

---

## Expected Behavior
- [ ] A component is needed to replicate a link with button functionality. This should be text coloured (to distinguish from links) and inverted on dark areas of UI.
- [ ] New documentation for sky.com/toolkit

## Current Behavior
There is no such component.

## Context
Panels - https://github.com/sky-uk/toolkit/issues/159
Other pieces of UI

**Comment by joebell93** [comment]
Existing PR - https://github.com/sky-uk/toolkit-ui/pull/210

**Comment by claredevine** [comment]
Existing PR for docs - https://github.com/sky-uk/polaris-page-producer/pull/1128
