### ISSUE TITLE
[Discussion] What improvements / changes would you like to see in Toolkit 2.0?

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit#186]
*Excluding breaking changes already mentioned in the [**2.0 Milestone**](https://github.com/sky-uk/toolkit/milestone/2)

**Comment by MrDinsdale** [comment]
- Responsive utilities i.e. `u-margin-top-large@medium`. Possibly `u-margin-horizontal-large` to apply left and right margins rather than adding them individually.
- Better debugging options to highlight in correct usage of toolkit classes maybe?

I'll get thinking on this!

**Comment by joebell93** [comment]
Ooh I like that `-horizontal` idea

I've been thinking something like `u-margin-x`, `u-margin-y` for some time, just concerned about bloat

**Comment by MrDinsdale** [comment]
Yep, same with adding responsive utilities.

Perhaps though this is a good argument to make it a little more granular. We have discussed adding extensions for Toolkit for different brands i.e. Mobile, maybe a similar approach could be used to add responsive utilities. If its opt in then bloat is a little less concerning for me however still not ideal and would mean less consistency between projects potentially.

**Comment by claredevine** [comment]
After the conversation in the Flow Selecta channel, rainbow text would be nice to see in 2.0.
Rainbow stuff is being rolled out slowly across the Sky estate and I think its a bandwagon toolkit should really jump on - as if loads of people are slowly using it we could be asked why we aren't aiding them.

**Comment by coderas** [comment]
I'd lie to see a DOM ordering utility/*nebulous* thing based on the tile->panel work  @steveduffin did

**Comment by MrDinsdale** [comment]
@claredevine We should get gradient text in Toolkit asap. It needs a little rework to allow for more than 2 colours but it should do nicely.

**Comment by claredevine** [comment]
@MrDinsdale sounds like a great solution! I'd happy to pair on it, if your happy to (or whoever is working on it)?

**Comment by joebell93** [comment]
@claredevine @MrDinsdale added to https://github.com/sky-uk/toolkit/issues/178

**Comment by joebell93** [comment]
As we have a backlog now fully defined for Toolkit 2.0, I'll close this issue.

Cheers guys!
