### ISSUE TITLE
The 'c-tile--full c-tile--media' selectors limit background images to 55%

### ISSUE THREAD

**Issue by mrazf** [sky-uk/toolkit#191]
PR coming from squadzilla asap

## Expected Behavior
c-tile--full's should have a 100% height background image

## Current Behavior
Being overridden to 55%

## Attempted Fixes
What have you done to mitigate this problem within your own application? Overriden it in diagnostics

## Steps to Reproduce (for bugs)
The [Full Tile](http://www.sky.com/blackjack/toolkit/components/tile) on the blackjack website has the image cut off

![screen shot 2017-03-09 at 14 06 58](https://cloud.githubusercontent.com/assets/15988613/23753531/b827476a-04d1-11e7-822f-6a6f5222407e.png)

**Comment by joebell93** [comment]
Cheers @mrazf, looking forward to seeing the PR!

**Comment by joebell93** [comment]
Closing as this is actually due to an [override in Sky Pages](https://github.com/sky-uk/sky-pages/blob/cc31815184af146cafce892090c133109925bf83/src/components/tile/common/_tile-overrides.scss#L11).
