### ISSUE TITLE
Update font-face sources

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit#205]
## Expected Behavior
Fonts should point to `sky.com/assets`

## Current Behavior
Fonts point to `assets.sky.com`

## Context
Masthead depreciation will remove the current font hosting

**Comment by csswizardry** [comment]
Also encourage people to `preload` their fonts to get around performance bottlenecks.

**Comment by csswizardry** [comment]
Also also trim down number of font files we’re using; only need one (maybe two) to hit IE9+.
