### ISSUE TITLE
Move font-face declarations higher up the CSS

### ISSUE THREAD

**Issue by csswizardry** [sky-uk/toolkit#207]
Given that:

1. fonts are late-discovered resources, and;
2. `@font-face` rules are inert…

…then we should actually probably move the `generic/_font-face.scss` import way  up to the top of the CSS file. It means they get discovered marginally* quicker, with zero impact on how things render and/or cascade/inherit.

* I stress the word _marginally_ here—this isn’t gonna speed the site up by 1000×, but ever little helps…

**Comment by joebell93** [comment]
Fancy firing up a PR? 🚀
