### ISSUE TITLE
Issue with Rails compiling assets - "File to import not found or unreadable: normalize.css/normalize."

### ISSUE THREAD

**Issue by JoeGuest** [sky-uk/toolkit#210]
## Expected Behavior
accessory-shop-tools to be able to compile successfully

## Current Behavior
`rake assets:precompile` is resulting in the error `Sass::SyntaxError: File to import not found or unreadable: normalize.css/normalize.`

## Attempted Fixes / Workaround
Using a previous version of toolkit, v1.10.0

(Had a quick chat with @joebell93 regarding this, was mentioned that perhaps reverting this change: https://github.com/sky-uk/toolkit-core/commit/949828eaf9b1fd58fa7bda9682549292c6b81cfc may be one way to resolve)

**Comment by joebell93** [comment]
Seems like this is a problem with Ruby Sass

I think for now it might be wise for you to adapt the future recommended way of installing Toolkit:

1. Include `toolkit-core` in your main view's `<head/>` as the very first stylesheet.
```
<!DOCTYPE html>
<!--[if IE 9 ]>               <html lang="en-GB" class="ie9"> <![endif]-->
<!--[if gt IE 9 | !IE ]><!--> <html lang="en-GB"> <!--<![endif]—>
<head>
  <link rel="stylesheet" href="https://www.sky.com/assets/toolkit-core/v1.12.0/toolkit-core.css">
</head>
...
```

2. Switch your current reference of `sky-toolkit-core/all` to `sky-toolkit-core/tools` in your main `.scss` file.

**Comment by joebell93** [comment]
Closing this as it's resolved through the "Hybrid installation"
https://github.com/sky-uk/toolkit#hybrid

Obviously, you won't be able to use the Node.js entry points, but using a hard-coded stylesheet tag will resolve this.
