### ISSUE TITLE
Default Divider has no shadow at the bottom.

### ISSUE THREAD

**Issue by afenton90** [sky-uk/toolkit#214]
Provide a general summary of the issue in the Title above

## Expected & Current Behavior
If you're describing a bug, tell us what should happen

When consuming the `Divider` styles in an app that uses webpack 2, the shadow style is being output as
```
.c-divider:after {
   background: radial-gradient(at 50% 0,rgba(74,74,74,.15),transparent 0);
}
```

The value in the docs app is:

```
.c-divider:after {
   background: radial-gradient(at 50% 0,rgba(74,74,74,.15),transparent 40%);
}
```

## Attempted Fixes
What have you tried to resolve this issue?
Using the latest version of sky-toolkit, has not resolved this issue.

What have you done to mitigate this problem within your own application?

## Steps to Reproduce (for bugs)
Provide a link to a live example, or an unambiguous set of steps to
reproduce this bug. Include code to reproduce, if relevant

0.
0.
0.
0.

## Context
How has this issue affected you?
Default styles not rendering.

Why is this change required?
To render default styles.

What problem does it solve?
Rendering default styles.

What program is it supporting? e.g. Toolkit evolution / Sky Mobile
Consistent styling.

## Your Environment
Include as many relevant details about the environment you experienced the bug in

* Version used: 1.15.0
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile): Mac OSX

**Comment by joebell93** [comment]
If you’re using cssloader in Webpack, it’s probably down to the imposed “safe” css nano rules
https://github.com/webpack-contrib/css-loader/issues/433#issuecomment-283637836

Keep us posted

**Comment by joebell93** [comment]
@afenton90 please can you confirm this was the issue? ☝️ 

If so, we can close

**Comment by afenton90** [comment]
Resolved as part of webpack config in project.
