### ISSUE TITLE
Tabs scrollbar spacing issue in Windows when overflow-x: visible and overflow-y: hidden

### ISSUE THREAD

**Issue by lnolazco** [sky-uk/toolkit#217]
The element has a scroll bar at the bottom even though I've specified visible and hidden values for overflow x/y.
- overflow-x: visible
- overflow-y: hidden

This only happens to browsers in Windows
![image](https://cloud.githubusercontent.com/assets/9590095/26199300/5b9ae066-3bc1-11e7-94d9-7f7975ad5168.png)

![image](https://cloud.githubusercontent.com/assets/9590095/26199971/0f8ea0ce-3bc4-11e7-9dd9-799c1326efd1.png)

In a Mac there is no scrollbar when is hidden
![image](https://cloud.githubusercontent.com/assets/9590095/26199733/07d6d2b2-3bc3-11e7-9e19-64301a45d32e.png)

![image](https://cloud.githubusercontent.com/assets/9590095/26199958/001871c4-3bc4-11e7-91f7-ffdf7d96dee8.png)

## Expected Behavior
It should be consistent.
Ideally if the scrollbar is hidden, it shouldn't add extra space at the bottom.

## Current Behavior
Adds space for the scrollbar bottom

## Steps to Reproduce (for bugs)
In the description of this issue I added screenshots from the components Tabs and Scrollable from the toolkit-react branch alpha.
To reproduce it you will need to run the toolkit-react locally
npm run preview
and open the application in a windows device (I used browserstack)

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
Lastest versions of:
- Chrome
- Safari
- IE
- Edge
- Opera

* Operating System and version (desktop or mobile):
- Windows 10
- Mac OS X Yosemite

**Comment by joebell93** [comment]
Is this still an issue @JamesPeiris?

**Comment by joebell93** [comment]
Closing as no further comments have been made on this issue
