### ISSUE TITLE
Tabs navigation width issue with many tabs

### ISSUE THREAD

**Issue by JamesPeiris** [sky-uk/toolkit#220]
## Expected Behaviour
Navigation bar is scrollable so latter tabs can be reached

## Current Behaviour

When the tabs component navigation bar exceeds the width of the container the latter tabs are not reachable as the bar is not scrollable. This is due to `width: auto` in `.c-tabs__header`
<img width="850" alt="screen shot 2017-05-22 at 17 16 15" src="https://cloud.githubusercontent.com/assets/2997151/26318435/fa3c2870-3f12-11e7-8839-b00b0edd5fe1.png">
However, when this is removed, navigation bars that are a fraction of the width of the container stretch to 100%, so the `width: auto` in `.c-tabs__header` is necessary.
<img width="849" alt="screen shot 2017-05-22 at 17 15 29" src="https://cloud.githubusercontent.com/assets/2997151/26318445/01e74a6e-3f13-11e7-9aa3-eac3d5481d2a.png">

The navigation not scrolling is only an issue when `fullWidthNavBar` is `false`, and in view modes where the width is not overridden to be `100%`

## Attempted Fixes
Remove `width: auto` in `.c-tabs__header` - but as mentioned this causes stretching when navigation should not be full width.

## Other Fixes
Could be considered a hack but could add an event listener that on resize/componentWillMount/update that compares the length of the navigation header with the container width - if the navigation width is larger than the container, set `fullWidthNavBar` to true, allowing for scrolling without requiring a design-breaking css change as in *Attempted Fixes*. 

## Steps to Reproduce (for bugs)
Start Sky Pages locally.
Go to the demo page.
Open the engagement panel.
Reduce the screen width until the last few tabs are out of view
Note that those few tabs are not accessible as they cannot be scrolled to

## Context
Found when testing the tabs component in Sky Pages

**Comment by joebell93** [comment]
Is this still an issue @JamesPeiris?

**Comment by joebell93** [comment]
Closing as no further comments have been made on this issue
