### ISSUE TITLE
Refactor of our `$gradient` map

### ISSUE THREAD

**Issue by MrDinsdale** [sky-uk/toolkit#223]
Currently the `$gradient` map consists of:

``` scss
$gradients: (
  large: (
    start: #cdccd4,
    end: #fff
  ),
  mid: (
    start: #e6e6ea,
    end: #fff
  )
  // ...
```

With the inclusion of Mobile we are starting to see use cases where adding more than 2 colour points is required.

We are considering moving to a slightly different, more flexible structure using the colour position as a key and hex as the value:

``` scss
$gradients: (
  large: (
    0%: #cdccd4,
    100%: #fff
  ),
  mobile-glint: (
    0: #ff7100,
    50%: #f00,
    100%: #5400ff
  )
  // ...
```

This would allow for and gradients with more than two colours and inclusion of colour start points.

To achieve this consistently we would need to update existing mixins to loop through the colour points defined in the map too.

This would allow us to remove the `background-page()` mixin and replace with our existing `background-gradient()` mixin using:

``` scss
$gradients: (
  // ...
  background-page: (
    0%: #c9c7d1
    6%: #e5e5ea
    20%: #fefefe
    80%: #fefefe
    94%: #e5e5ea
    100%: #c9c7d1
  )
);
```

Would be great to get any feedback on this.

**Comment by skitson** [comment]
I think it's the way forward!

**Comment by joebell93** [comment]
Yup, love it. Go for it!
