### ISSUE TITLE
Git Strategy

### ISSUE THREAD

**Issue by csswizardry** [sky-uk/toolkit#224]
I think we need to decide upon and formalise an approach to our use of Git for this project. Everything feels quite unorganised and disparate right now and I would really like to tidy things up, make them a lot more strict, and a lot more repeatable. The upshot(s) would be

* it becomes easier to navigate our way around commits/issues/branches;
* it’s more clear what we should do in more ambiguous scenarios;
* a reduction in the likelihood/frequency of conflicts;
* a nicer, neater, tidier place to work.

At a high level I recommend:

* **Branches named after issues (e.g. `tkt-00123`)** means that we know exactly where to look for work pertaining to a specific feature/bug/task.
* **Commits starting with that issue number (e.g. `[refs #00123]`)** mean that GitHub can automatically link things up for us, and then our `log`s become `grep`pable.
* **Commit messages sourced from a template** so that we have a neat and uniform style (and avoid poorly formatted messages).
* **Automation** to reject malformed commit messages.
* **`CHANGELOG` and version bumps only happening in `master`** means no more stepping on toes by version bumping in feature branches—versions should _only_ exist in the consumed branch (i.e. `master`).

**Comment by joebell93** [comment]
Absolutely agree this is something we need to resolve, but with current deadlines, I don't think we can justify too much time on this right now

I've popped it in `Up Next` on our Project Board, let's discuss as soon as we release Toolkit 2.0
