### ISSUE TITLE
Releases, CHANGELOGs, Version Bumps

### ISSUE THREAD

**Issue by csswizardry** [sky-uk/toolkit#225]
**This is a long-lived issue.**

When rolling official releases, we need to bump the version in `package.json`, populate a CHANGELOG, and tag the relevant commit in the `master` (or `release/v2`) branch. Do that against this issue so that we can see an aggregated list of them.

**Comment by joebell93** [comment]
As part of this issue, I'm going to suggest we also look at tidying up our NPM scripts to move towards an automated publishing process
