### ISSUE TITLE
[Feature] Multi-line text truncation

### ISSUE THREAD

**Issue by Rory1994** [sky-uk/toolkit#233]
## Expected Behavior
We had a desire on the sports watch page (http://www.sky.com/watch/channel/sky-sports) to truncate the titles of sports content to 2 lines. 1 line truncation is supported in basic CSS but multi-line is more tricky and we felt it would be good for their to be a universal CSS solution to support multi-line truncation (and we didn't want to butcher the CSS ourselves into Sky pages). 

Currently solution for text truncation in Sky Pages involves just limiting the amount of characters in a title to a fixed number which isn't flexible.

Would be sick if this was a thing

**Comment by yoniholmes** [comment]
If/when text truncation lands in toolkit, someone should ping the Digital Engagement team (or just raise a PR) to undo this hardcoded character limit which was a workaround:  https://github.com/sky-uk/sky-pages/blob/7cc83b7732eb2c76e03baaf6bb5eb162a0710f98/apps/watch-channel/server/convert-to-gallery.js#L10. Ideally CSS alone could truncate overflowing text with an ellipsis.

**Comment by joebell93** [comment]
@yoniholmes @Rory1994 cool, let us know how you get on finding a solution!

**Comment by MrDinsdale** [comment]
Currently there isn't really a pure CSS solution for this (to my knowledge) so it will need to remain a JS based solution.

A better approach might be to look at adding utils for `toolkit-react` to implement this?

**Comment by joebell93** [comment]
I'll close this as it seems to be fairly use-case and the issue's a bit stale
