### ISSUE TITLE
[Feature] Roundel Component

### ISSUE THREAD

**Issue by jamie-sky** [sky-uk/toolkit#253]
## Expected Behaviour

As part of Sky Mobile we have created a 'Roundel' component which is used to select the variant of a given product. For example, selecting the colour of a phone. We feel that this should be introduced to Toolkit because it is a key piece of functionality throughout the Sky Mobile user journey and feel that it could be beneficial to other sales flows within Sky. 

The Roundel component is basically a radio button. It is to be included as part of a form and it's purpose is to set the value of a selected product variant. For example, a phone's colour or storage size. 

The Roundel component is currently available in three different forms (see screenshot below):
- A Roundel with a Colour
- A Roundel with a Label
- A Roundel with an Icon.

When a user selects a Roundel it's border colour will change to indicate a selected state. 

<img width="595" alt="screen shot 2017-07-19 at 11 06 49" src="https://user-images.githubusercontent.com/29920350/28361937-69f44a80-6c72-11e7-86f5-17e1315b2972.png"> 

## Attempted Fixes

N/A - New Component Request

## Context

This component is currently used within Sky Mobile.

## Your Environment

N/A - Not a bug

**Comment by joebell93** [comment]
Nice overview @jamie-sky 🎷 

Let's get Alan Abbott to give it a run through and see if this is something for use over the whole estate before we look at adding it into Toolkit

**Comment by jamie-sky** [comment]
Cheers @joebell93 - sounds good to me.

**Comment by apabbott** [comment]
Cheers Joe. At the minute this is a specific pattern for mobile, mainly handset selection. With a more unified approach to buying across the estate in the not too distant future, accessories shop etc. I think it would be a good addition to the toolkit.

**Comment by joebell93** [comment]
So how does this differ to the current `select` component @apabbott?

https://www.sky.com/toolkit/components/select

**Comment by StefanMcCready** [comment]
Functionally this is the same kind of thing, the problem with the select component is that you cant really use it for visually displaying variations such as colour. It really limits itself an item of a single variant, also if you have a lot of them it looks a bit terrible.

**Comment by apabbott** [comment]
Within accessories we have products with, in excess of, 10 colour variations. Visually and spatially this creates a problem the standard select button can't solve.

Basically, what Stefan just said!

**Comment by joebell93** [comment]
Sweet, so are we potentially looking at a modifier of the Select component here? or would you say this is something different altogether?

(also guessing we have visually hidden text in these roundles too for accessibility?)

**Comment by joebell93** [comment]
Paging @mikejgregory

**Comment by jamie-sky** [comment]
Hey Joe. We've gone with the intention of this being a separate component altogether. The discussions around why etc took place before my time at Sky! But I imagine it's because there are a number of visual differences between this and the Select component. Implementing this as a modifier of Select would just cause unnecessary bloat, this component can also be used in a range of ways (showing product colour, display text for capacity or an icon) and I'm making the assumption that the designers came to the conclusion that the UX around the Select component for this purpose just wouldn't work as well. I'm sure @StefanMcCready or somebody else involved in the decision process before my time can step in and correct/elaborate though!

**Comment by mikejgregory** [comment]
Afternoon.  If possible it would be great if we could bring the build inline with design.  Not sure why but this was never built as per design.  This seems the perfect opportunity to finish the component. The main points are:
- The grey keyline should be the only outline on the non-selected state.  IE no white inner boarder.
- The selected state should have the larger blue circle with a white inner boarder.  Currently the selected state is smaller than the non-selected state.  It should be bigger.

Happy to talk over this if it helps.

![screen shot 2017-07-21 at 16 25 42](https://user-images.githubusercontent.com/17929557/28470323-4d756752-6e31-11e7-88a9-6f6517decc11.png)

**Comment by rachel-goulding** [comment]
<img width="341" alt="screen shot 2017-07-27 at 12 15 55" src="https://user-images.githubusercontent.com/14804015/28668210-b83a509a-72c6-11e7-839b-7c0d5ddd8d04.png">

**Comment by apabbott** [comment]
Can we please make the white key line on the selected state thinner? 
On Mike's design it is 2px. The above example is significantly thicker.
The thickness helps to contain the design more. Especially when it's a number rather than a colour that has been selected.

**Comment by joebell93** [comment]
@apabbott sounds like there's already been a verbal agreement on this between @rachel-goulding and @mikejgregory - can I suggest you speak to Rachel and make sure any agreement is written in this issue for confirmation and future reference?

**Comment by jamie-sky** [comment]
I've just had a chat with @rachel-goulding now I'll make the changes as per @apabbott's comments now and update the PR. Cheers!

**Comment by joebell93** [comment]
Can we make sure that whatever's agreed on is written here to confirm?

**Comment by jamie-sky** [comment]
@rachel-goulding please can you provide your stamp of approval on this issue following our chat on Slack to make the changes that Al suggested. In the mean time @joebell93 I'll attend to your feedback on the PR now - thanks 👍

**Comment by rachel-goulding** [comment]
Hi All, I thought i had commented on this...i'm happy to make the amends as per Al's suggestion.

**Comment by joebell93** [comment]
Awesome!

**Comment by mikejgregory** [comment]
In order to bring the build inline with design please change the animated selected state to the blue border fading in (instead of panning in).  It's my understanding that this will enable the removal of the white inner padding and create a smoother animated transition for hover and selected states.
