### ISSUE TITLE
[a11y] hide-visually() mixin is not as accessible as it could be

### ISSUE THREAD

**Issue by stowball** [sky-uk/toolkit#258]
## Expected Behaviour
When text with spaces is accessibly hidden, it should be announced as a proper sentence.

## Current Behaviour
Text with spaces can be smushed together and spoken as 1 long word. See https://medium.com/@jessebeach/beware-smushed-off-screen-accessible-text-5952a4c2cbfe.

## Suggested Fix
Add `white-space: nowrap !important;` to [`hide-visually()`](https://github.com/sky-uk/toolkit/blob/develop/packages/sky-toolkit-core/tools/_mixins.scss#L62).

**Comment by joebell93** [comment]
Just released this, cheers @stowball

I'll be in Sydney 7th-10th November; if you're nearby I'll buy you a coffee as a thanks!
