### ISSUE TITLE
Card Component

### ISSUE THREAD

**Issue by StefanMcCready** [sky-uk/toolkit#262]
## Expected Behaviour
Within Shop we are currently in the process of redesigning how we show products. It is a desire to have an identical design across the board to give a consistent look and feel. The plan is for certain apps within service that will want to use this component as well. Below is a diagram detailing the anatomy of the card:

![screen shot 2017-07-26 at 10 36 38](https://user-images.githubusercontent.com/14904083/28614618-5830074a-71ee-11e7-97bd-3e4fc716da0e.png)

## Context

Mentioned in the overview where it wants to be used. Below is a list of more specific projects that will use it for product display. It can also be used for other things is designers see fit.

* Sky Mobile Sales
* Sky Mobile Service
* Accessory Shop
* Shop

**Comment by joebell93** [comment]
How should this shadow compare to Tiles @mikejgregory?

**Comment by StefanMcCready** [comment]
It shouldnt ;-)

**Comment by joebell93** [comment]
_Compare_

**Comment by mikejgregory** [comment]
When this was created there was no knowledge that the shadows had tiles / if this was even a thing.  I'll catchup with Bryson to talk this over.

**Comment by joebell93** [comment]
Sweet, give me a shout if you need any clarification @mikejgregory

**Comment by mikejgregory** [comment]
It's been agreed that the card shadow styling will remain as designed and will not impact the tile shadow for now.  The intention is to revisit the tile designs for toolkit 3.0.
