### ISSUE TITLE
Guild Meeting Notes - 09/08/2017

### ISSUE THREAD

**Issue by StefanMcCready** [sky-uk/toolkit#264]
Things to discuss:

 - [x] Calender Expansion
 - [x] Documentation
 - [x] Storybook - linked to docs
 - [x] Scrolling in toolkit-react panel - https://github.com/sky-uk/toolkit-react/issues/58
 - [x] General Issues

Actions to take:

- [x] Raise calendar / date-picker / time-picker / table / data-previewer in #design-web (Clare to do)
- [ ] Potential hack day / afternoon for backlog - make some sick readmes (Speak to josh about sessions and pizzas and monies)
- [ ] Consider whether maintainers and champions is something that should be reconsidered. Maybe have all on an equal footing?
- [ ] Review guidelines for being a maintainer

**Comment by joebell93** [comment]
Nice work @StefanMcCready 👍 

To review your actions:

1. What's the issue? @claredevine could you update me please
2. Can't do this until we have dedicated resource sadly 🙃 
3. I don't think that's a good idea, Toolkit's is a high-use product across the estate. Maintainers should be totally fluent and confident enough to write scalable CSS and roll out features on their own. Champions are equally as beneficial, but the responsibilities are much higher and I don't think it's wise to share them.
4. Good shout, just need time

**Comment by claredevine** [comment]
@joebell93 just raised in #design-web 😄
