### ISSUE TITLE
Look into running Autoprefixer on pure Sass

### ISSUE THREAD

**Issue by aaronthomas** [sky-uk/toolkit#27]
We can run Autoprefixer as part of our build process to save us manually writing vendor prefixes.

Autoprefixer doesn't have to run on compiled CSS, so we can run it against our Sass files and distribute them prefixed.

**Comment by joebell93** [comment]
I'm going to suggest we close this for now until it becomes a pressing issue

I think for now we should deliver prefixed CSS (it should just work) and utilise `/*! autoprefixer: off */` protection
