### ISSUE TITLE
Pricing to get Footnote Symbols

### ISSUE THREAD

**Issue by steveduffin** [sky-uk/toolkit#270]
## Expected Behaviour

New requirement shared across Loyalty and Rose to provide footnotes to `price`. `Price` should allow an additional symbol to be added after the cost to indicate which footnote they are referring to.

![screen shot 2017-08-17 at 15 55 09](https://user-images.githubusercontent.com/1849493/29464353-88871888-842d-11e7-8f6f-6093827927e6.png)

The footnote text itself can be a `<ol class="o-list-bare c-text-smallprint">..</ol>` i.e requires no change in toolkit
However, the symbol itself is going to require some toolkit work

## Current Behaviour

The current styling of `price` and `costing` prevents us from being able to position the symbol correctly. 
Toolkit changes will need to account for:
- Strike through should not cover the symbol 
- Absolutely positioned pence in`costing`
- Pence being omitted in `costing`
- Colour of price *should* effect the symbol i.e Orange for sale, grey for stirkethrough

## Attempted Fixes
- Toolkit : https://github.com/sky-uk/toolkit/pull/271
- Toolkit-react Issue: https://github.com/sky-uk/toolkit-react/issues/227
- Toolkit-react PR: https://github.com/sky-uk/toolkit-react/pull/228

## Context
Upcoming changes for Rose
Pending work for Loyalty

**Comment by joebell93** [comment]
I'm kinda confused, if it's no change in CSS then does this need to be an issue? 🙂

**Comment by steveduffin** [comment]
Take a look at the WIP #271 I've just added.
It's fair light touch in price but costing is going to need some extra work to get the symbol in the right spot (pence is absolutely positioned)

**Comment by steveduffin** [comment]
The footnote text itself won't need toolkit changes. The symbol **will**. Edited the text above to make that a little clearer.
