### ISSUE TITLE
[Bug] Colour Roundel Safari Issues 

### ISSUE THREAD

**Issue by jamie-sky** [sky-uk/toolkit#273]
## Expected Behaviour

The Roundel Colour selector should render consistently across browsers.

## Current Behaviour

When viewing the Roundel Colour Selector in Safari there is an issue where the colour indicator is misaligned and not set to the correct width, see screenshot below.

<img width="170" alt="screen shot 2017-09-05 at 14 13 28" src="https://user-images.githubusercontent.com/29920350/30062878-a284aa6e-9244-11e7-8f5d-40dcf0255fea.png">

## Steps to Reproduce (for bugs)

We haven't launched Bundled Accessories for mobile yet so unable to provide steps to recreate from Sky website. However, viewing the colour selector Roundel in Safari will present the issue.

## Your Environment

Issue was found in Safari 10.1.2

**Comment by mikejgregory** [comment]
I'm happy with the improvements Jamie has made to vertically and horizontally centre iconography within the roundels.  Results seen here.
![screen_shot_2017-09-06_at_11 47 18_720](https://user-images.githubusercontent.com/17929557/30163755-0c9fc0e4-93d2-11e7-85fd-ce06cce87689.png)
