### ISSUE TITLE
Forms select input - visual clipping

### ISSUE THREAD

**Issue by lukewhitehouse** [sky-uk/toolkit#279]
## Expected Behaviour

The select box should always clip text in order to provide space for the icon, however, there should also be space to the left of the icon to match the padding to the right of it.

## Current Behaviour

The select box visually clips too close to the left of the icon. This is much more distracting when the character in question is larger (i.e. capital G) and I'm sure there will be issues for users with lower quality monitors.

![screen shot 2017-09-12 at 11 08 59](https://user-images.githubusercontent.com/2808486/30322224-a1543c24-97b0-11e7-919f-ffff2bc5cd4b.png)

## Attempted Fixes
This is going to depend on feedback from design. However, a proposed solution would be to make the following changes:

```sass
.c-form-select::before {
    /* From */
    width: 40px;

    /* To */
    width: 65px;
}

.c-form-select__dropdown {
    /* From */
    padding: 5px 20px 5px 10px;

    /* To */
    padding: 5px 40px 5px 10px;
}
```

Which will result in the screenshot below.

<img width="312" alt="screen shot 2017-09-12 at 11 56 54" src="https://user-images.githubusercontent.com/2808486/30322480-85d01bfc-97b1-11e7-9d84-a2d975c04784.png">

Although values could probably be tweaked.

## Your Environment

This is an issue in both Chrome, Win7 IE11 and most likely all other browsers.

**Comment by MrDinsdale** [comment]
This looks like it is caused by the reduction in `$global-spacing-unit-large` which has reduced the gradient width from 60px to 40px while the icon size has remained at the same size. This is a good example of where a fixed value would be better that one based on our global spacing unit.

**Comment by MrDinsdale** [comment]
@lukewhitehouse 60-65px seems reasonable.

**Comment by lukewhitehouse** [comment]
@MrDinsdale Cheers Joe. What is recommended here then, create a variable specifically for forms, (i.e. `$forms-spacing-unit` or something similar) or hardcode the px value in?
