### ISSUE TITLE
Overlay component

### ISSUE THREAD

**Issue by aaronthomas** [sky-uk/toolkit#288]
## Expected Behaviour
We have demand for a new Overlay component, which takes the form of a fullscreen "takeover" with a narrow fixed position header and footer.

The UI has already been approved at a design level.

I suggest we implement this agnostic of both content and context. The component should simply render an empty overlay which can be implemented in any layout.

## Current Behaviour
This currently does not exist.

## Context

This is currently a demand of the Rose programme, but is also present in Mobile (Sales & Service), Loyalty, and Soundbox.

**Comment by aaronthomas** [comment]
I'll be picking this up this week.

**Comment by joebell93** [comment]
Just checking, what's the use-case here? What would be inside the takeover?

**Comment by aaronthomas** [comment]
As an example, we're going to be using this to display more info about each Sports channel.

I believe Mobile's use case is similar: displaying more details on individual handsets.

**Comment by joebell93** [comment]
Cool, so not too dissimilar to a panel

What's the key difference/value in having another contextual information component?

**Comment by aaronthomas** [comment]
Can't fit `500vh` worth of content in a panel 😀 

It's mostly marking material, lots of full-bleed images etc.

**Comment by joebell93** [comment]
I've got ya, if we're having both it would be good to get some guidelines on this design-wise to ensure there's a solid use-case for each one
