### ISSUE TITLE
Docs revisit

### ISSUE THREAD

**Issue by MrDinsdale** [sky-uk/toolkit#298]
We should revisit the steps for contributing and releasing to make sure all required steps are fully covered. Currently our releasing docs don't cover running `lerna bootstrap` etc.

I think for the majority everything is clear however I think we could benefit from starting from scratch and running through everything to make sure nothing has been missed that could cause people issues.

**Comment by joebell93** [comment]
Added to https://github.com/sky-uk/toolkit/issues/297
