### ISSUE TITLE
Remove Sky brand specific assets from Toolkit when served to third parties

### ISSUE THREAD

**Issue by skitson** [sky-uk/toolkit#301]
## Current Behaviour
At present we supply Toolkit users with the `Sky Text` font and colours by default regardless of whether they are Sky developers or third parties.

This is mainly a problem associated with the pre compiled and hosted version of Toolkit.

## Suggested Behaviour
We need to restrict the use of Sky assets to Sky projects only and serve third parties with a version that does not include those assets.

Let's discuss potential ways of achieving this with the least amount of pain for Sky developers and third parties using the Toolkit as an open source tool.

**Comment by lukewhitehouse** [comment]
Off the top of my head, what about a structure like this:

```
- sky-toolkit: provides the UI and Core layers.
-- sky-toolkit-core: Global styles and defaults for all projects.
-- sky-toolkit-ui: Aesthetic components.
-- sky-toolkit-brand: Styling associated to the Sky brand.
```

This could get strange when we start thinking about different components that consume Sky colours though. How far do we need to go with this? i.e. do we have versions of `Overlay` that has Sky branding and one that doesn't?

**Comment by skitson** [comment]
Yeah that's a route @steveduffin is investigating now and it feels like the right thing to do.

I think the main one is protecting usage of the `Sky Text` font (it's served as the primary font family in the compiled hosted version) and also colours that are specific to the Sky brand.

We could split something like colours out into the brand/theme layer but there would have to be some changes with core around serving the `Sky Text` font as default (@MrDinsdale reminded me that there is already a way to change the default font that is provided).

It might be that we compile the hosted version with the `Sky Text` font removed as the primary font as a quick intermediate solution.

I think we also need some sort of disclaimer in the docs about using the Sky brand without permission.

**Comment by skitson** [comment]
And in relation to your question about examples of third parties - I don't think it matters. The only thing that should matter is that they are a party not affiliated with Sky.

**Comment by lukewhitehouse** [comment]
Another thought is if the only things we need to change are variables then we could override the defaults? I'm guessing this is what @mrdinsdale mentioned to you?

**Comment by MrDinsdale** [comment]
Personally I don't think we should worry about providing a non-Sky version of the hosted Toolkit. The hosted version is provided for rapid prototyping and isn't really designed to be used by 3rd parties and I think adding a non-sky toolkit is encouraging that.

**Comment by skitson** [comment]
I get what you're saying Joe, and I agree that it might encourage third parties to use the hosted version. I just think that if it's there, available to third parties to put into their work then there's a danger that a less experienced third party or one that doesn't know how to use SCSS or node/npm will think it's okay using it as is, fonts and all.

**Comment by lukewhitehouse** [comment]
I would agree with @MrDinsdale though, catering for third parties can quickly try and make Toolkit into something anyone can use (like a Bootstrap alternative). I'm assuming the focus of Toolkit will always be for Sky, even though it's Open Source. If that's the case then I think keeping Toolkit opinionated is a good thing. Or am I misinterpreting?

**Comment by MrDinsdale** [comment]
I think perhaps misuse of the font is probably the biggest issue here which we should get some clarity on. There was a discussion about the font use in the past, prior to setting the repo to public although no harm in double checking.

**Comment by joebell93** [comment]
I'm honestly not too worried about this, and I think it adds a layer of complexity

It may, however, be worth revisiting the license if this is still a concern @skitson 

@Tom-Davidson what do you think?

**Comment by joebell93** [comment]
I'm going to suggest we close this as it's gone fairly stale and there hasn't been any comment since November

Feel free to open back up!
