### ISSUE TITLE
Introduce responsive c-divider classes

### ISSUE THREAD

**Issue by skitson** [sky-uk/toolkit#302]
## Expected Behaviour
Introduce the ability to apply the c-divider at set breakpoints. For example - we would end up with the ability to use `c-divider@medium` to apply the c-divider from our medium breakpoint.

If we make the modifier classes responsive too we can also move the divider around between breakpoints: `c-divider--right@large` for example.

## Current Behaviour
The current behaviour is to display the divider regardless of breakpoint.

## Context
This would solve the problem of having to hide the divider manually. It's often the case that a divider is no longer needed when below medium breakpoint, especially if applied to layout containers that become single column.

**Comment by skitson** [comment]
I've built a branch that responsivizes the `c-divider` class but doing this adds about 700 more lines of compiled CSS.

Not sure that we want to do that...

**Comment by skitson** [comment]
@MrDinsdale suggested looking at a modifier to hide the divider at breakpoints using `$from` and `$until` values. Not sure about this one...

**Comment by skitson** [comment]
Just putting it on the `c-divider` class generates about 280 extra lines.

**Comment by joebell93** [comment]
280 extra lines 😰

**Comment by joebell93** [comment]
What do we still think about this?

**Comment by skitson** [comment]
I think the general consensus was the extra lines outweighed any benefits and people were better implementing their own solutions if needed.

**Comment by joebell93** [comment]
OK, I'll close for now!
