### ISSUE TITLE
Possible solution to the `faux-link` conundrum 

### ISSUE THREAD

**Issue by MrDinsdale** [sky-uk/toolkit#303]
I know the f-word has been discussed a lot for some time but I would like to propose a very simple solution. This is a long term change but we could look at ways to gradually introduce it in a non breaking manner.

After speaking to @mikejgregory it seems that from a design stand point there is no interest in the markup used for buttons/links, only appearance. This to me seems like a similar scenario to heading use where we want to separate semantic markup from visual styling.

Rather than looking to make additional classes such as `c-link-faux` to handle these use cases which are becoming increasingly common I'd suggest the following simple alternative:

- `c-btn` continues to be compatible with both `a` and `button` elements.
- `c-link` is adapted so that it also resets button styling therefore being available to both `a` and `button` elements by default.

Much like headings this separates semantic markup from styling and results in more intuitive usage.

**Comment by skitson** [comment]
I think this is the way to go - it will save a lot of future confusion and potential clashes.

**Comment by StefanMcCready** [comment]
All for intuitive usage, makes sense to go down this route

**Comment by steveduffin** [comment]
Does this need to be a separate issue from https://github.com/sky-uk/toolkit/issues/286? - I know that got muddied with talk about the component used for close buttons

**Comment by MrDinsdale** [comment]
@steveduffin Thats a good shout, I thought that got closed.

Having said that I will keep this open and raise a PR to demonstrate this approach. If people are happy with it then we can look at planning a roll out.

**Comment by steveduffin** [comment]
No worries. I'll just leave this here: https://codepen.io/steveduffin/pen/LzdJpj

**Comment by MrDinsdale** [comment]
@steveduffin It's just a happier world.

**Comment by joebell93** [comment]
I think it probably makes sense to close this PR and continue within @steveduffin's original one- otherwise things will get confusing

**Comment by steveduffin** [comment]
Closing: Solved in 2.8.0 https://github.com/sky-uk/toolkit/blob/v2.8.0/packages/sky-toolkit-ui/CHANGELOG.md
