### ISSUE TITLE
Toolkit/Design alignment

### ISSUE THREAD

**Issue by MrDinsdale** [sky-uk/toolkit#304]
Myself and @mikejgregory will be running through latest designs and working to align our toolkit styles with the design asset library.

We will go through and make all the changes required then form a plan for releasing, some changes are likely to be breaking so would need to wait for V3 etc with appropriate deprecation warnings etc.

**Comment by MrDinsdale** [comment]
TODO:

- [ ] Align dropdown and forms with new sizing

**Comment by joebell93** [comment]
I've created a new milestone for this: [Design Alignment](https://github.com/sky-uk/toolkit/milestone/3)

**Comment by MrDinsdale** [comment]
As we have broken up stuff here in to separate tickets and milestones I think we can close this ticket.
