### ISSUE TITLE
Create Modal component

### ISSUE THREAD

**Issue by MrDinsdale** [sky-uk/toolkit#306]
The Modal exists in a number of areas including sky.com/mobile-account and sky.com/mobile.

Additional information and designs coming soon (@mikejgregory)

**Comment by joebell93** [comment]
I'm interested to hear more about this - what makes it different to an overlay?

Cautious of us having two things that are slightly different in appearance

**Comment by MrDinsdale** [comment]
@joebell93 The modal is designed to sit above the existing page, with the background obscured. @mikejgregory would it be possible to get a real world example/mock up of how this in use?

Maybe we should be looking to collect more information at this stage of a component for guidelines on usage etc from design? It could help us with implementation perhaps and give more context.

**Comment by mikejgregory** [comment]
Visit - https://www.sky.com/shop/mobile/phones/apple/iphone-8-plus?phone=14631 and click on payment breakdown.
![model](https://user-images.githubusercontent.com/17929557/33026859-63af5fb8-ce09-11e7-9e9d-935efb066c88.png)

**Comment by joebell93** [comment]
Is this exclusive to mobile so far @mikejgregory?

**Comment by joebell93** [comment]
Blocking this until we have a better direction on its purpose and design from the design team

**Comment by lukewhitehouse** [comment]
Hey guys I’m looking to build this for Accessories which will be based on the stuff for Mobile so I can build it with reusabiloty in mind and create a PR for Toolkit that gives us something to work from?

If the design changes later so be it but at least we’ll have something we can iterate on. Thoughts?

**Comment by aaronthomas** [comment]
Sounds like thats a third use-case so I'd say lets make this happen!

Regarding purpose and usage, all the examples of both overlays and modals that we have seen are very different use cases – both with regard to context and the style of content they display. I think there is definitely call to have both exist – but of course we'll still need guidance from Design on exactly what scenarios call for which component.

**Comment by joebell93** [comment]
Design-wise this is unfortunately still blocked until we have assets that are final and consistent - at the moment it's still in its early stages

**Comment by lukewhitehouse** [comment]
Is there no chance we can create something for the time being and iterate on it afterwards? I appreciate we'll want to standardise this but I feel this will at least give us some immediate standardisation? I'm sure we could do it in a way that doesn't cause any breaking changes too.

**Comment by joebell93** [comment]
Absolutely, I'd suggest doing this within your app (as if you were writing in Toolkit) and we extract later

**Comment by aaronthomas** [comment]
Doing it within your app is the opposite of standardisation :(

Totally agree we should be following Toolkit procedure here, so happy to stick with it for now, but I think this is a good example of why we may need to revisit that procedure to ensure it works well for all of us and we don't have this same debate every single time somebody tries to contribute a new feature.

**Comment by StefanMcCready** [comment]
Its being used in three different applications, the design hasn't changed in 18 months, the context of use is pretty clear, Im struggling to see why its blocked.

**Comment by StefanMcCready** [comment]
Much like Aaron mentioned, maybe we need to look over certain parts of the process, this conversation keeps happening over and over again suggestion something either isnt clear, or isnt working

**Comment by joebell93** [comment]
@aaronthomas 

>Is there no chance we can create something for the time being and iterate on it afterwards?

For this reason, it's far better to build within the app. I totally appreciate your concerns about standardisation, but we need to let that develop on the design side first. It might make sense for us to start re-using code, but we need to let this process and communication grow whilst the new library is being built, otherwise, we risk falling out of sync again. This won't be as rigorous when we are 100% aligned.

---

@StefanMcCready you're not taking into consideration the vast amount of work Mike's doing at the moment to do work on alignment. This is early stages, please be patient. See above.

**Comment by StefanMcCready** [comment]
Im fully aware on the alignment work going, dont need reminded about it.

**Comment by lukewhitehouse** [comment]
@joebell93 Okay thanks 👍

**Comment by mikejgregory** [comment]
I'm happy for the modal to be built guys as per mobile.  This is the design we have in our Sketch library too.  Seems simple to me unless I'm missing something.

**Comment by joebell93** [comment]
@lukewhitehouse go! I have forwarded you the assets via Slack
