### ISSUE TITLE
Interactions - Design Alignment

### ISSUE THREAD

**Issue by MrDinsdale** [sky-uk/toolkit#308]
## Expected Behaviour
Interactions should all have the same height/vertical alignment. They should all have a height of `40px` and `20px` left and right padding unless full width.

![screen shot 2017-11-20 at 13 22 43](https://user-images.githubusercontent.com/2472440/33020362-f2fc6512-cdf5-11e7-96ff-b9a9884b838d.png)

Components include:

- [ ] Button
- [ ] Form
- [ ] Dropdown
- [ ] Accordion
- [ ] Select

## Current Behaviour
These component vary in size quite dramatically as does the padding of the element.

**Comment by joebell93** [comment]
I'm thinking short-term we create a mixin to keep this consistent across all of our interactions

**Comment by MrDinsdale** [comment]
I remember the 40px line-height rather than line-height + padding on `c-form-input` was due to an IE10/11 issue. We will probably have to trial which method works best for all, if neither works for all instances we could always pass an option to the mixin to switch between the 2 approaches?
