### ISSUE TITLE
Inconsistent `line-height` across browsers

### ISSUE THREAD

**Issue by MrDinsdale** [sky-uk/toolkit#309]
## Expected Behaviour
Line height for our base font-size (18px) should be 26px.

## Current Behaviour
We need to do a little investigation however as it stands our line-height values compute incorrectly on chrome (25px) but fine in Firefox.

## Attempted Fixes
Needs additional investigation however changing the `line-height` value from `1.44` to `1.45` seems to resolve but we need to test further.

**Comment by joebell93** [comment]
Is this still an issue now @MrDinsdale ?

**Comment by joebell93** [comment]
Discussed with @MrDinsdale and we're going to close this until it becomes an issue
