### ISSUE TITLE
Checkbox tick placement

### ISSUE THREAD

**Issue by MrDinsdale** [sky-uk/toolkit#311]
## Expected Behaviour

Currently the tick should be centrally aligned on the checkbox.

![on](https://user-images.githubusercontent.com/2472440/33019936-3dcaca90-cdf4-11e7-9dac-c5af845f18db.png)

## Current Behaviour
Checkbox tick appears off centre, aligned to the bottom
<img width="253" alt="screen shot 2017-11-20 at 15 09 47" src="https://user-images.githubusercontent.com/2472440/33025108-e2becd70-ce04-11e7-82ff-2bbba0cd010e.png">

Reduce size of tick slightly and move up so that it appears to be visually centred.

**Comment by joebell93** [comment]
I'd disagree with this one - it doesn't account for when our checkbox line needs to wrap onto another line 

Pretty sure a checkbox in the middle of 3 lines will look super weird

**Comment by MrDinsdale** [comment]
@joebell93 Sorry, didn't explain well, this is referring to the tick icon within the checkbox rather than the text. Will add a screen shot to show the current placement and explain a little better!

**Comment by MrDinsdale** [comment]
After zooming for a good image it doesn't look that bad :D It appears more noticeable at small scale though.

**Comment by joebell93** [comment]
Ah ok! Do we think this worth our time looking into?

**Comment by MrDinsdale** [comment]
@joebell93 To be honest it does look wrongly positioned on our checkbox, I'd argue it's at least worth 10 mins to see if it can be cleaned up a little and align better with design. I don't think its a high priority however.

**Comment by MrDinsdale** [comment]
Perhaps minor reduction in size with slight tweaks to placement:

Before:
<img width="122" alt="screen shot 2017-11-21 at 12 17 43" src="https://user-images.githubusercontent.com/2472440/33072108-0a37e4de-ceb6-11e7-8570-8e85e0090c43.png">
After:
<img width="119" alt="screen shot 2017-11-21 at 12 17 30" src="https://user-images.githubusercontent.com/2472440/33072107-0a2104c6-ceb6-11e7-95ea-eb046478f348.png">

It looks a little cleaner and aligns better with design.

**Comment by joebell93** [comment]
Is this something you'd want to pick up instead and we'll remove from the Design Alignment milestone?

**Comment by joebell93** [comment]
Think it's fair to say this ticket has gone stale, with it being self-assigned in March with no action taken

Closing
