### ISSUE TITLE
Gradients - Spectrum

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit#317]
## Expected Behaviour

Although Sky's logo fill isn't _strictly_ a gradient (more of a blurred mesh of colors), it would still be beneficial to provide a linear "spectrum" gradient to match it.

## Current Behaviour

N/A

## Context

Alignment with the design team

**Comment by lukewhitehouse** [comment]
This may or may not be useful but this is the one we were going to use for Soundbox until we removed them completely:

```
sky-spectrum: (
  0%: #ffba01,
  30%: #f6001f,
  50%: #dc008c,
  70%: #192cba,
  100%: #2199cd
)
```

**Comment by MrDinsdale** [comment]
Interestingly the values from the design library are:

``` scss
spectrum: (
    0%: #f08300,
    30%: #e3000f,
    60%: #a72879,
    100%: #0644a1
)
```

Probably a good example of why it might be beneficial to have :D

**Comment by lukewhitehouse** [comment]
Definitely, this was something @mikejgregory and I discussed when I was creating the gradient.

**Comment by joebell93** [comment]
I can confirm that @MrDinsdale's values are the correct ones
