### ISSUE TITLE
Clear indication of component specific variable usage

### ISSUE THREAD

**Issue by MrDinsdale** [sky-uk/toolkit#323]
## Expected Behaviour
Component defined variables shouldn't be used externally and are purely defined for internal use.

We could look to move any variables which could be beneficial to global usage into settings.

## Current Behaviour
There is no messaging to outline correct usage. As these are more likely to change, using externally is a risk.

**Comment by MrDinsdale** [comment]
Thinking something along the lines of:

```
// Settings (Not for use externally)
$btn-font-size: ...
```

**Comment by joebell93** [comment]
Sounds pretty similar to what @steveduffin's suggested in #319 

I'd suggest merging together and resolving as one issue rather than fragment

**Comment by steveduffin** [comment]
Agreed. Merged!
