### ISSUE TITLE
External Link with Tooltip - UI Bug

### ISSUE THREAD

**Issue by umpox** [sky-uk/toolkit#344]
## Expected Behaviour
Tooltip opens without affecting UI of link

## Current Behaviour
External link 'arrow' breaks onto new line within the tooltip

Hover:
![image](https://user-images.githubusercontent.com/9516420/34037718-be1eb4e0-e181-11e7-9c98-a52e0d7a4fba.png)

Normal:
![image](https://user-images.githubusercontent.com/9516420/34037730-c94057ca-e181-11e7-9e6f-9e758cc81da8.png)

## To replicate
Using Toolkit React:
```
<Link
  href="https://www.sky.com/"
  text="Link with tooltip"
  external
  tooltip={{
    isActive: true,
    text: 'Tooltip'
  }}
/>
```

**Comment by joebell93** [comment]
Can you please explain the use-case? 

External Links should only be used as **external links**, it's not intended for Tooltip usage.

**Comment by MrDinsdale** [comment]
I'd agree with @joebell93 on this however that being said probably shouldn't break. A little context as to why this is needed in this format would be helpful.

**Comment by umpox** [comment]
There's no specific use case in mind here @joebell93, the issue was found when following documentation on `toolkit-react`to add the component to Storybook, which is why it was originally raised on TKR. 

Are we discouraging the use of tooltips on Links entirely? If so, I can remove it from the Link storybook and the docs on `toolkit-react` to avoid confusion. 🙂

**Comment by MrDinsdale** [comment]
I think it would be good to get @mikejgregory to give some input. It's not something we would typically have for external links (or any links) as tooltips usually are set on more info `?` buttons. Perhaps we just need a little guidance on when and where these should be used.

**Comment by joebell93** [comment]
To be honest I don't think we need Mike's clarification on this one, it's a given - Tooltips are one of the things that have been highlighted in terms of inconsistency 

For now, I think we'll take up on your offer to remove it @umpox, thank you!
