### ISSUE TITLE
Subsection Dividers - Gradient Alignment

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit#348]
## Expected Behaviour

As defined in the internal Sketch Library, we have additional modifications for our **subsection dividers only** - left-aligned and right-aligned (where the gradient aligns to the edge rather than the center)

![image](https://user-images.githubusercontent.com/7349341/34255036-a84951b0-e646-11e7-9404-f3a631e175d0.png)

(you can just about make it out in the above image if you open in a new tab)

## Current Behaviour

No such feature exists, subdividers created in https://github.com/sky-uk/toolkit/pull/347

## Attempted Fixes

I propose that we simply create a `.c-divider--align-left` this way it **could** easily be used for either the standard divider or sub divider later.

Separating this out to a different component would just create unnecessary duplication

## Context

Design Alignment

**Comment by joebell93** [comment]
Would also like to open up the question of "do we really need this"?

@MrDinsdale raised a very valid point that this seems to be a bit of an anti-pattern if it's just for subsection dividers

**Comment by joebell93** [comment]
In terms of implementation, I suggest we add two new modifiers:

- `.c-divider--align-left`
- `.c-divider--align-right`

**If** this needs to be scoped to Subsection dividers we can simply do something like:

```
.c-divider--sub {
  .c-divider--align-left {}
  .c-divider--align-left {}
}
```

If this doesn't need to be scoped now (or in the future, we can release this as a non-breaking change)

**Comment by MrDinsdale** [comment]
I think (as touched on in https://github.com/sky-uk/toolkit/pull/347) should be the first decision before we attempt to include any form of the sub divider.

1) Do left and right aligned dividers need to exist.
2) If so can the same logic apply to standard dividers.

Once we know the outcome of this the correct solution for #347 should be clear.

Yep, its definitely an antipattern for BEM, what ever we do modifiers shouldn't require other modifiers to work correctly.

**Comment by MrDinsdale** [comment]
@joebell93 Scoping modifiers to other modifiers is surely an anti-pattern though? I think it makes the classes unpredictable and confusing to the end user with no real benefit.

**Comment by joebell93** [comment]
I've done some investigation into implementing this and it would require adding a breaking change to our `divider-gradient()` mixin

Right now, our divider gradient properties are `direction` and `color`. For ease of use, we've made this colour a default value so developers don't really have to worry about adding the correct value. For example:

```scss
@include divider-gradient();

// or

@include divider-gradient(right);
```

If we want to add an alignment property to this mixin, adding it to the end of our property declarations isn't really viable as we'll lose that default colour setting. Ideally, to achieve this we want our properties to be in the order of `direction, alignment, color` 

```scss
@include divider-gradient(left, center);

// is way nicer (and more rigid) than

@include divider-gradient(left, color(grey-20), center);
```

but doing this would **break** all existing implementations of the mixin...

**Comment by joebell93** [comment]
So is this _really_ something we need?

cc @mikejgregory

**Comment by mikejgregory** [comment]
This is a pattern available in design and has been ever since I've worked here.  Seems it's just not been implemented.  Understand there's issues in dev with this but for the moment it's a pattern that's required from design.

**Comment by joebell93** [comment]
How much is this being used @mikejgregory 

I don't think it's worth investing significant effort in this unless we can see it's a common pattern/requirement

**Comment by joebell93** [comment]
Closing this as we've achieved aligned dividers. Perhaps one to revisit at a later refactor
