### ISSUE TITLE
Remove leading zeroes on commit refs

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit#357]
## Expected Behaviour

Adding padding to our issue refs doesn't really provide any long-term value and causes more pain to our contribution process than it needs too.

Our commits should simply be written as:

```
[refs #355] Add static modifier to c-card component
```

## Current Behaviour

Currently, as defined in our [`CONTRIBUTING`](https://github.com/sky-uk/toolkit/blob/develop/CONTRIBUTING.md#committing-workflow) guidelines and [`.git-commit-template`](https://github.com/sky-uk/toolkit/blob/develop/.github/.git-commit-template) we pad our refs to 5 digits:

```
[refs #00355] Add static modifier to c-card component
```

## Attempted Fixes

Discussion within maintainers who agree it is unnecessary, PR to follow after further discussion with contributors.

## Context

Ease of Toolkit contribution

**Comment by lukewhitehouse** [comment]
As a generic contributor I don't mind if we have leading zeros or not, I imagine this specific problem will be more beneficial to core maintainers.

What might help is to not require the `[ref ###]` at all in commits, that'll help with the ease of Toolkit contribution but maybe that's going to be contentious. Eager to hear what other non-core contributors feel about this?
