### ISSUE TITLE
Inertial Scrolling within Overlay

### ISSUE THREAD

**Issue by zishan-ali** [sky-uk/toolkit#363]
Currently within the Toolkit Overlay Inertial Scrolling is not available within mobile devices as pointed out by @berlin-sky in http://jira-psp.cg.bskyb.com/browse/DTV-60

## Expected Behaviour
When scrolling on mobile devices it should feel more natural, though as of current it feels throttled. 

## Current Behaviour
When scrolling on mobile devices it should feel more natural, though as of current it feels throttled. 

## Attempted Fixes
After discussion with @aaronthomas the fix is something that should ideally live within toolkit as the issue is not app specific.

## Context
Inertial Scrolling within the Overlay on mobiles is not available. This was discovered while testing `in-page-upgrades`

## Your Environment
All browsers // occurs on mobile.

**Comment by joebell93** [comment]
To be honest, I'm a bit confused by this one as it's just native scroll behaviour:
https://github.com/sky-uk/toolkit/blob/develop/packages/sky-toolkit-ui/components/_overlay.scss#L87

I suspect there may be some other issue in the implementation you're looking at that's causing a throttled appearance

Not too keen on modifying the default scrolling behaviour, imo we should leave that to the browser/device to decide.

**Comment by aaronthomas** [comment]
@joebell93 

In iOS, native scroll behaviour is different on anything other than the document itself. You don't get "momentum" scrolling on any element other than the window.

What Zishan is suggesting is adding the `-webkit-overflow-scrolling: touch;` property to the overflow content, which will enforce native-style momentum scrolling on the element.

**Comment by steveduffin** [comment]
In iOS, anytime you declare an overflow, Safari removes inertia scrolling from the effected element (as we are doing at https://github.com/sky-uk/toolkit/blob/develop/packages/sky-toolkit-ui/components/_overlay.scss#L90); you have to explicitly redeclare touch as the scrolling behaviour to get the natural scrolling behavior back. The difference is night and day.

**Comment by joebell93** [comment]
I get you, makes sense

So in that case is it worth adding a simple mixin to ensure we get this scrolling consistent across core/components?

**Comment by steveduffin** [comment]
Darn it @aaronthomas beat me to it

**Comment by steveduffin** [comment]
Might be a little premature to abstract this right now; the only other component I can see benefiting is `tabs` but it's questionable whether you would want that "elastic" scrolling when picking from a list of links
