### ISSUE TITLE
Hero component with no shine

### ISSUE THREAD

**Issue by kamaltmo** [sky-uk/toolkit#372]
## Expected Behaviour

We need to be able to use the Hero component without the shine. There are instances in design where background hero images are used without the current shine that all heroes have. Ideally modifier class to disable those styles needs to be implemented.

## Current Behaviour

Whenever the Hero component is used a shine and shine rails are added to the bottom of the image. This limits the use cases of the component and forces people to rebuild it/use custom CSS when the shine is not in design 

## Attempted Fixes

I am currently using the following, an ideal solution would also remove the Div at a TKR level, however, that's for another PR.

```
// The ability to remove all shine from Heros
.c-shine-none {
  &::before, &::after {
    content: none;
  }

  .c-shine__rail {
    &::before, &::after {
      content: none;
    }
  }
}
```

## Context

An upcoming Sky Q Journey trading has requirements for this functionality.

**Comment by joebell93** [comment]
You simply don't include `.c-shine` in your markup, this sounds like more of a TKR issue

**Comment by kamaltmo** [comment]
ah, so we are okay to move on adding the ability to remove it in TKR? @joebell93   Didn't want to add the ability to remove it if it deviated from how Toolkit wanted the component to be presented 👍
