### ISSUE TITLE
input fields marked required should not be presented as errors

### ISSUE THREAD

**Issue by steveduffin** [sky-uk/toolkit#375]
## Expected Behaviour
An input with `required` set on it should add a astrix but not have a red border by default

## Current Behaviour
Inputs marked with `required` are presented with a red border making them look like there is an error before the user has taken action.
This is because a browser will consider any required input as invalid until it's requirements have been satisfied.

![screen shot 2018-02-22 at 11 41 39](https://user-images.githubusercontent.com/1849493/36536583-5ead6338-17c5-11e8-8c3d-edc4d899168a.png)

## Attempted Fixes
Remove `c-form-input:invalid` from the styling https://github.com/sky-uk/toolkit/blob/30a32004eb20b1402318c211df4858abfaa7d6b6/packages/sky-toolkit-ui/components/_forms.scss#L472

## Steps to Reproduce (for bugs)

Recreated in codepen: https://codepen.io/steveduffin/pen/aqKqzE?editors=1000

## Context
Spotted when working on Sky's react pattern library 

## Your Environment

Include as many relevant details about the environment you experienced the bug in

* Version used: 2.14
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome 64
* Operating System and version (desktop or mobile): macOS 11.13

**Comment by joebell93** [comment]
I'm not sure about the removing the `:invalid` solution just yet, as it does provide useful indication in things like email/phone text fields (HTML validation)

**Comment by steveduffin** [comment]
Leaving  `:invalid` means we get a red border around every field with a `required` property - surely it's not right to be presenting a form fields that look like errors before any interaction has taken place?

The astrix is our one design pattern to indicate required.

Do we need a new style to mark out fields that have yet to have user interaction or have native errors? That's essentially what you are getting with :invalid and we already have `is-error` to mark validation issues.

**Comment by joebell93** [comment]
Two ideas:
1. Set the `:required` border to same colour as default.
2. Add `::not(:required)` under line 473.

**Comment by markwoodward23** [comment]
Just come across this too and agree with @steveduffin, it seems weird! Think the consuming application should be handling the validation and therefore the application of the `error` state?

**Comment by steveduffin** [comment]
Either of @joebell93 options will work to unset the red border and mean the consuming app will be responsible for setting error state by passing the `is-error` class.

`::not(:required)`  is my preference as it's a bit more obvious what's being unset and safe to do without changing existing behaviour for renegades setting `c-form-required` but not `required` (like us on the docs 😝 )
