### ISSUE TITLE
Remove `::after` from Radio Buttons

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit#376]
## Expected Behaviour

Replace `background-image: none;` with `content: normal;` to reset our pseudo element.

## Current Behaviour

Currently, our `.c-form-checkbox--radio` sets our `::after` background-image to `none`. This is inefficient and blocks use of pseudo-elements for our consumers.

## Attempted Fixes

See solution above in expected behaviour.

## Context

Currently affecting a spike by @steveduffin

**Comment by steveduffin** [comment]
This pleases me

**Comment by joebell93** [comment]
Fixed in https://github.com/sky-uk/toolkit/pull/381
