### ISSUE TITLE
Fix long label on accordion

### ISSUE THREAD

**Issue by TomGB** [sky-uk/toolkit#377]
## Expected Behaviour
If an accordion has a long label (like 5 or more words) then the label text should wrap onto the next line. The text should also not overlap the dropdown button.

## Current Behaviour
Currently text that is too long in the label overlaps the second label.
It also overlaps the drop down arrow.

![Example](https://user-images.githubusercontent.com/5748077/36978340-187f5316-207c-11e8-9586-7dfba0245592.png)

Can be found on: https://pre-production-watch.herokuapp.com/help/articles-development/returning-sky-q-equipment
When screen width is below 470px.

## Attempted Fixes
Currently some css has been used locally in our apps to fix the new line bug.
But this issue is found on many pages across sky.

## Steps to Reproduce (for bugs)
https://pre-production-watch.herokuapp.com/help/articles-development/returning-sky-q-equipment
resize window so width is below 470px.

## Context
This affects many of the articles which are about to be released on
https://sky.com/help/articles/****
Currently it makes the accordions ugly and difficult to use and understand.

## Your Environment
The bug appears in all environments.

**Comment by joebell93** [comment]
Awesome thanks for finding, let us know how you get on with a fix.

**Comment by joebell93** [comment]
https://github.com/sky-uk/toolkit/pull/378
