### ISSUE TITLE
Extract Hero Text Shadow for re-use

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit#379]
## Expected Behaviour

If we're applying `text-shadow` to elements, it should be the same across the board and accessible via `$global-text-shadow`.

## Current Behaviour

Currently, we only have this variable available in Hero as `$hero-text-shadow`.

## Attempted Fixes

Move the value of the Hero text shadow to globals for re-use.

## Context

Wanting to use for Internal Estate

**Comment by joebell93** [comment]
@claredevine are you still working on this? If not I'm hoping to pick this up and get out

**Comment by claredevine** [comment]
@joebell93 yes, just commiting now
