### ISSUE TITLE
New gauge component

### ISSUE THREAD

**Issue by aaronthomas** [sky-uk/toolkit#384]
A new component to show varying levels (speed, capacity, quantity etc.) on a circular dial.

I have spoken with @mikejgregory and confirmed this as a reusable pattern.

Examples:
![screen shot 2018-03-19 at 14 33 04](https://user-images.githubusercontent.com/1419558/37601650-7e344110-2b82-11e8-93e7-b70ba2162f35.png)
![screen shot 2018-03-19 at 14 33 15](https://user-images.githubusercontent.com/1419558/37601651-7e4d6a46-2b82-11e8-94aa-f8502959ea95.png)

This component is initially required for the new Broadband journeys, however use cases have been identified in Mobile (sales and service) and there is potential for use in other areas.

I'll be picking this up shortly.

**Comment by joebell93** [comment]
Can I suggest we look at building this within Broadband first, and once we're satisfied extract later to avoid prematurely adding to our design library?

**Comment by aaronthomas** [comment]
@joebell93 Happy to. 

Curious though, if this has been approved by design as a reusable pattern, and already has more than 3 use cases, what's the reason for building elsewhere first?

**Comment by joebell93** [comment]
@aaronthomas it's not necessarily the fact that it has 3 use cases, but it would allow the chance for the component to mature to a production-ready state and lessen the risk of a breaking change in the near future

Perhaps a component that would be perfect to kick off @steveduffin's `beta` branch proposal?
https://github.com/sky-uk/toolkit/issues/359

**Comment by joebell93** [comment]
@sky-uk/toolkit as Aaron's no longer here to work on this with us 🎻 and no-one else seems to be taking ownership of this I'm going to suggest we close until it's ready to introduce
