### ISSUE TITLE
Should we extend our default Grid settings?

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit#390]
## Expected Behaviour

Should we extend our width utilities to `1/6`? Should we go all the way to `1/12`s?

## Current Behaviour

Currently, we only provide up to `1/5`.

## Context

Cropped up in a couple of areas, let's see if this becomes more common. 

If this affects you, please log your examples here.

**Comment by lukewhitehouse** [comment]
Update: We had a guild session on the 28th March 2018 where we discussed this issue. There was a lot of back and forth on the subject, weighing up the pros and cons of adding the extra classes and whether or not the potential bloat was worth it. For now we agreed to keep to our [Rule of 3](https://github.com/sky-uk/toolkit/blob/master/CONTRIBUTING.md#requirements) and pick this up again if/when we get to a point where multiple teams require this functionality.

**Comment by joebell93** [comment]
@lukewhitehouse this was written up in response to that same guild session 😄 

Thanks for expanding what was discussed though!

**Comment by steveduffin** [comment]
Hold up. I thought we agreed the solution was to extend to 6 to allow nesting of grids to accommodate design's 12 col layout? And then revisit a full 12 col layout if there was enough examples of nesting

**Comment by MrDinsdale** [comment]
@steveduffin I'm not sure there was a unanimous decision past monitoring the situation and use cases. 

If we have sufficient examples of where 6 columns would be beneficial then we should look at adding 1/6.

**Comment by MrDinsdale** [comment]
Just as a side note, if we changed the way we generate `widths` to account for duplicates adding up to 12 columns would be a much smaller jump in size.

Rather than outputting equivalent values such as:
`1/2`, `2/4`, `3/6`, `4/8`, `5/10` and `6/12`

We could reduce this to only out put the lowest common value `1/2`. This would add complexity to the tools though. I know there are a few instances where we programmatically calculate the correct width values, which would have to account for this too.

**Comment by joebell93** [comment]
Whilst it may reduce the size, I think this would add unnecessary complexity to usage (i.e. if someone's using `6/12` with `2/12` and a `4/12` it's easier to grasp the whole picture immediately)

**Comment by joebell93** [comment]
What if we found a way to still output them but instead share the value?

e.g.

```
.u-width-1/2,
.u-width-2/4,
.u-width-3/6 {
  width: 50%;
}
```

Although I'm not sure how much difference this would make

**Comment by steveduffin** [comment]
Our lead designer has asked us to support a 12 column grid, my understanding is that every design going forward is underpinned by a 12 column grid. It's been mentioned that after gzip, the size of core goes from 4.4kb to 9kb. These are tiny numbers in the grand scheme of things. For me, thats justification enough to bake support in

**Comment by joebell93** [comment]
So I was just about to fire up a PR to get `1/6` into Toolkit and opened up a can'o'worms in Slack.

---

Some background: 

### File Size

- `sky-toolkit-core` with our widths up to fifths comes in at `34.7kb` (`4.4kb` gzip)
- `sky-toolkit-core` with our widths up to sixths comes in at `34.7kb` (`4.9kb` gzip)
- `sky-toolkit-core` with our widths up to twelfths comes in at `91kb` (`9.3kb` gzip)

---

### Reasons against 12-column by default

- 90% of the time you [**really don’t need** 12 columns](https://www.smashingmagazine.com/2017/12/building-better-ui-designs-layout-grids/). Items are are grouped sensibly into fractions that are readable, simple and easy to understand.
- What happens to everything in between? Are people realistically going to use `1/7` `1/9`, `1/11`? Where do we draw the line?
- Modern web principles (such as CSS Grid) encourage grouping, not 12 column.
- 12 column can be achieved if needed via the mixins in Supercell.
  - **However**, we add additional responsive classes. Perhaps we could get started by making this easier to extend? A `$global` setting? 
- 12 column can be achieved by nesting if we add `1/6`.
- 12 column more than doubles the size of `sky-toolkit-core` if all fractions are added.
- "12 column only" is a significant breaking change

---

### Proposal

1. We add `1/6` to instantly allow for nesting to create 12-column
2. We make the default setting much easier to extend, perhaps via a `$global-layout-widths` variable?

Seeing how people get on with the above, we can then get on with the possibility of introducing 12 column. Whilst it might seem like a small size in the grand scheme of things, I think that's an assumption that everyone wants the same feature. Let's give devs control over their performance, rather than force this upon everyone when quite often it's not needed.

**Comment by lukewhitehouse** [comment]
Just to play devil's advocate on a few of those points you made @joebell93 

1) Currently yes, however as has been made apparent, design are going to be making designs based on 12 columns pretty much from now on. How much longer will it in 9 times out of 10.
2) Sure, CSS Grid will help, but we've already had discussions before about there still being a need for supercell outside of CSS Grid Layout.
3) 4) 5) They can be achieved, but in light of 1) at what point should this be the default.
6) I really don't think 9kb is something to worry about IMO. We have much bigger problems on performance gains than our CSS but maybe thats just me.
7) True that would be a breaking change, I don't think it adds much bloat adding it as an addition though.

Be eager to hear other peoples thoughts. I need to catchup on the rest of this thread!

**Comment by steveduffin** [comment]
# Reasons for 12-column by default

- Our designers use a 12 column grid. Conversations with them often include discussion of "this is 10, this is 7" etc, if we should be sharing the same design terminology as much as possible.  
- Prevent fudging with margin and padding. I've seen developers adding extra margin to accommodate the extra gutters needed to prevent content from getting too wide and align closer with the source design.
-  No mental arithmetic required - is 10/12s the same as 4/5? Doesn't matter, a one to one is much easier to understand
- Performance is is important, however, developer sanity rules over micro optimisations in almost every instance. 
- Toolkit sets a standard. We are embracing 12 column layouts as a standard, why should developers have to use a mixin to generate defaults?
- Is adding 12 columns really a breaking change? All the previous fractions would work as they do now, would there not just be extra fractions to choose from?

**Comment by joebell93** [comment]
@lukewhitehouse @steveduffin before I provide counterpoints to each of your arguments, what do you think about the proposal I have suggested above? Keen to hear thoughts on that before continuing this discussion

**Comment by joebell93** [comment]
@lukewhitehouse cheers for that!

>I think a 6 column width would help alleviate the initial hurdle of allowing for layouts like this out of the box, however, if a design did require 12 columns then that would require more markup in order to have layout widths within layout widths, which I don't think is healthy for the long term in a project of any size.

That's a fair point, and part of the reason I'd like to track it and see how it goes.

>I'm not too sure what you're getting at with this? Could you expand on the idea? How would that help? Would that give us access to update 1 2 3 4 5 found in our supercell implementation or something?

Yeah basically! As we wrap out widths around breakpoints, extending them now isn't easy. So for example, if you only want `×/12`s units, you have the option to do so. This gives full control to the devs and avoids wasted units:

```scss
$global-widths: "12" // or "1 2 3 4 5 6 7 8 9 10 11 12" if you *really* wanted;
@import "sky-toolkit-core/all";
``` 

on the design front, I feel like the Smashing Magazine article answers this well. Mike isn't too fussed on how we implement it, I think as long as we provide the ability to set this where needed, that's fine. I haven't seen enough of a use-case to warrant adding all fractions up to twelfths (which is the only way to do this non-breaking)

I'll save going into too much detail on my counter argument until Steve's shared his thoughts on the propsal

**Comment by lukewhitehouse** [comment]
@joebell93 I think the addition of the 6 columns and the global variable would be a good first pass at this and as you say see how it goes. That's got my vote unless we find out that 12 columns is definitely going to be the way forward for the most part.

**Comment by steveduffin** [comment]
Which part of the the Smashing magazine article are you refering to? 
if its this:
> While the 12-column grid is a popular choice among many designers, it’s not a one-size-fits-all solution. When you choose a grid, select one with the number of columns you really need for your design. There’s no point in using a 12-column grid if your layout needs only 8 columns.

The answer is, we have chosen a 12 grid. It's correct that it's not obvious in many designs, but it does underpin every design at sky.

Your proposal is a smart way to get us to a 12 column grid without supplying a 12 column grid. 
IMO however, that's not right, it should be 12 out the box without any work at the consumer level. 

Ultimately, if we have to make a compromise, this 1/6 grid + variable is probably the best one until there is enough evidence of demand. (With the increasing adaptation of mono repos / templates, it will be hard to know what that tipping point looks like)

**Comment by joebell93** [comment]
Cheers @steveduffin, as we move towards getting CSS bundles within these monorepos, I'm hoping it'll be easier for us to track where these customised widths exist, and hopefully help us to unanimously agree on a new set of defaults for Toolkit

**Comment by joebell93** [comment]
@lukewhitehouse @steveduffin I've raised a PR for the proposal above: https://github.com/sky-uk/toolkit/pull/416. Please can I get your reviews on this?

Then I'm going to suggest we close this issue until we hear more use-cases for generating the full suite by default
