### ISSUE TITLE
<legend> elements shouldn't be hidden in a radio button group context

### ISSUE THREAD

**Issue by sekhavati** [sky-uk/toolkit#397]
## Expected Behaviour
When creating a set of radio buttons the recommended way of applying a label to the group (_not_ an individual option) is to use a `fieldset` combined with a `legend`. When done so, the expectation is that the legend text is visible.

## Current Behaviour
In toolkit we hide all `legends`'s unconditionally (see [here](https://github.com/sky-uk/toolkit/blob/develop/packages/sky-toolkit-core/elements/_forms.scss#L13)). 

## Attempted Fixes
_What have you done to mitigate this problem within your own application?_

Rolling with a `<p>` tag in the mean time.

## Steps to Reproduce (for bugs)
Our own documentation demonstrates this bug in action:

https://www.sky.com/toolkit/components/forms#radio-buttons

**Comment by lukewhitehouse** [comment]
This probably needs design factoring in as if design aren't using `legends` in their form styling then that needs to change before we know what and how to style them?

**Comment by steveduffin** [comment]
I've come up against this issue while looking at how checkboxes an radio buttons handle display of errors. We really shouldn't be hiding this information. 

I suggest we introduce a class to `c-forms` to make the hide opt in and remove the `legend` selector from https://github.com/sky-uk/toolkit/blob/138d332744e765a0e0bc2d02106aff4261627655/packages/sky-toolkit-core/elements/_forms.scss#L13 in 3.0. Something like `c-form-legend`

Meanwhile, we also add a class in `c-forms` that overrides the hide, something like `c-form__group-legend`
