### ISSUE TITLE
Jekyll Sass compiler issue 

### ISSUE THREAD

**Issue by ScottGuymer** [sky-uk/toolkit#401]
## Expected Behaviour
When consuming toolkit from within Jekyll you should be able to compile the Sass files and generate a bundle.

## Current Behaviour
Sass compiler throws an error when compiling a bundle that includes tookit

the error is 
```
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'resources/css/main.scss':
                    Invalid CSS after "...eys of `#{$keys": expected "}", was "...}` in the de..." on line 107
```

It appears to be caused by this line

https://github.com/sky-uk/toolkit/blob/develop/packages/sky-toolkit-core/tools/_functions.scss#L107

## Attempted Fixes
Removing the ellipsis seems to fix the issue.

## Steps to Reproduce (for bugs)

Provide a link to a live example, or an unambiguous set of steps to
reproduce this bug. Include code to reproduce, if relevant

0.
0.
0.
0.

## Your Environment

Include as many relevant details about the environment you experienced the bug in

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

**Comment by joebell93** [comment]
Just tried removing the ellipsis, replacing to:

```
@warn "Unknown keys of `#{$keys}` in the defined map";
```

Worked perfectly
