### ISSUE TITLE
Modal scrolling in different browsers

### ISSUE THREAD

**Issue by zishan-ali** [sky-uk/toolkit#415]
## Current Behaviour
In the current modal, (and I believe we've come across this in the overlay too?) in various browsers - namely Firefox and other MS browsers we have unnecessary scrollbars appearing that were otherwise not appearing in Chrome. 

For this issue specifically we have a horizontal scrollbar appearing in Firefox but not in Chrome - within the modal when open - even though no text is overflowing? 

Contact me for an example

## Attempted Fixes
(-)

I believe some sort of `overflow-x: blah` would sort this issue but I haven't attempted a fix.

## Steps to Reproduce (for bugs)
Visit any webpage implementing the current TKR modal component in Firefox 🤷‍♂️ 

## Context
Not a massively urgent/needed change though still weird behaviour being experienced, I don't see this as blocking our implementation of a modal within our new BBNT template inside the internal React.js framework (contact me for an example) though something that possibly still needs resolving. 

## Your Environment
* Version used: (-)
* Environment name and version (e.g. Chrome 39, node.js 5.4): Firefox Quantum (latest)
* Operating System and version (desktop or mobile): Desktop

**Comment by zishan-ali** [comment]
Related to https://github.com/sky-uk/pages-lib/issues/205

**Comment by minnypatel** [comment]
importing scss dependencies in the order specified in https://github.com/sky-uk/pages-lib/pull/212 prevents this bug. 
For a potential deeper fix, see https://github.com/sky-uk/pages-lib/issues/151
