### ISSUE TITLE
[Modal] Close Label

### ISSUE THREAD

**Issue by zishan-ali** [sky-uk/toolkit#433]
**Is your feature request related to a problem? Please describe.**
We've received a requirement to hide the close label in certain situations and have also seen that the toolkit has document a solution to support that. After an initial implementation in our internal component library `pages-lib` where `u-visually-hidden` could be supplied to the relevant span depending on whether a boolean prop is passed. 

We further received dev feedback off the back of this implementation that this may cause inconsistencies across the estate and people could dictate the Modal's UI on a project-by-project basis, and that this should be controlled. Following further clarity from design from BA's and Design we've been given the direction to always hide the close label on mobile and show it on desktop. For this reason I'm proposing some work to hide the close label on mobile.

**Describe the solution you'd like**
I've already worked on a solution on a PR within `pages-lib` where the close label is hidden on mobile using a simple sass media query. 

**Describe alternatives you've considered**
An alternative I've already tried is mentioned above where `u-visually-hidden` is supplied depending on if a prop gets passed to the component during implementation.

**Additional context**
(-)

**Comment by joebell93** [comment]
Right I get you, so are you thinking something like

```scss
.c-modal__close-label {
  // Media Query
}
```
