### ISSUE TITLE
Panel component using breakout mixin causing specificity issues

### ISSUE THREAD

**Issue by lukewhitehouse** [sky-uk/toolkit#436]
**Describe the bug**

Since [the introduction of the breakout mixin](https://github.com/sky-uk/toolkit/pull/388/files#diff-13c2c6e2554356aa870481ee1a192e8cR31) the `c-panel` has started using `!important` on its styles. This is making it difficult to override unless we also use `!important` in our apps, which is never a good idea.

**Attempted Fixes**

Few options I can think of to go with:

1) Remove the `breakout` mixin from the `c-panel` and bring the component back to its previous implementation of the same styles the mixin brings through but without `!important` applied to them.

2) Remove `!important` from the breakout mixin itself.

3) Accept that this is now a thing and the only way to update the styling (including the `width` in my case) is to use `!important`.

Personally, I don't think 3 is an option and we should go with either 1 or 2. Eager to hear a few thoughts on this so I can create a PR for it.

**How has this issue affected you?**

Sky Mobile are using the `c-panel` and overriding the `width` property to use viewport units for some custom styling in the app.

**Comment by joebell93** [comment]
>Sky Mobile are using the c-panel and overriding the width property to use viewport units for some custom styling in the app.

It would be good to understand _why_ this is the case before we discuss solutions, also considering this change was released in March

**Comment by lukewhitehouse** [comment]
@joebell93 Without getting into the nitty-gritty, these are older styles that could do with being refactored. Theres an argument to say that we should refactor them, however, the time it'd take to do so is considerably more time than it would to update to do the other options.

> this change was released in March

Yep, this has been a problem since March, its just that because this is in such an obscure place in our app that we haven't seen the error until now.

**Comment by joebell93** [comment]
>Theres an argument to say that we should refactor them, however, the time it'd take to do so is considerably more time than it would to do the other options.

If that's the case I'm wondering if this is really a Toolkit issue or an issue with your app's implementation? To be honest, I think it's the latter

However, there is another PR (https://github.com/sky-uk/toolkit/pull/432) where I proposed a `@include mixin(reset)` for our mixins, perhaps we could look at another `@include mixin(important)` option. Perhaps worth discussing in there? Still, I think removing the important now would be a breaking change

**Comment by steveduffin** [comment]
`!important` is such a dangerous tool, we should build in the facility to allow for more deliberate implementation. I can see the justification when a mixin is building out a utility but when it makes it's way into components, we have problems like the above and #432. We wouldn't condone use of `!important` in a component so styles brought in from a mixin should be no exception. 

I like the idea of being able to pass arguments to mixins to alter the specificity and/or reset itself. 
For now we could make accommodations to mixins on a case by case basis, keeping the default as is to avoid breaking changes. 
Then for `3.0` we roll out to all mixins using !important and set the default to be `!important` free?
