### ISSUE TITLE
switch to static.skyassets.com

### ISSUE THREAD

**Issue by jbwatson** [sky-uk/toolkit#437]
**Is your feature request related to a problem? Please describe.**
This isn't really a feature request but its not a bug 😄 

Switching hardcoded `//www.sky.com` urls to `//static.skyassets.com` would result in those assets being served up quicker to frontends due to less akamai contention on the domain. 

**Describe the solution you'd like**
Switch `//www.sky.com` urls to `//static.skyassets.com`

**Describe alternatives you've considered**
NA

**Additional context**
Toolkit is already served up under this domain e.g. https://static.skyassets.com/assets/toolkit-core/v2.20.0/toolkit-core.min.css so no additional config required other than path changes.

**Comment by joebell93** [comment]
Do you know if this something for sure we'd be happy to have publicly?

**Comment by jacktams** [comment]
We are serving a whole of static content from that other domain these days, its secured and fronted by the same akamai slot as www.sky.com. 

As we are being pushed by various stakeholders to improve site performance, removing contention on sky.com is one of the big wins for across the entire estate.

**Comment by joebell93** [comment]
I'm happy to change this, it's just more about the fact that this repo is public and this `cdnUrl` is public - if that's ok then let's do it

**Comment by lukewhitehouse** [comment]
Sounds like a nice little tech debt ticket for us to tick off then 👍

**Comment by joebell93** [comment]
To reiterate, we need to confirm this URL is OK to be public

**Comment by lukewhitehouse** [comment]
@joebell93 makes sense, but I think its safe to assume that's the case otherwise we wouldn't be able to use the CDN links on the public facing website.
