### ISSUE TITLE
Update maintainers

### ISSUE THREAD

**Issue by joe-bell** [sky-uk/toolkit#439]
**Is your feature request related to a problem? Please describe.**
As I'm leaving it's probably worth removing me from the README 😢 

**Describe the solution you'd like**
Eternal happiness

**Describe alternatives you've considered**
I switched from my usual Kettle Chips flavour of Salt and Vinegar to Sour Cream and Chilli. 5/7 would try again

**Additional context**
I'll miss working with you all @sky-uk/toolkit

**Comment by lukewhitehouse** [comment]
This description is pure gold. Also 😢

**Comment by joe-bell** [comment]
@StefanMcCready slight delay in closing this issue
