### ISSUE TITLE
Set guidelines and structure for documentation

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit#44]
- Templates of good documentation
- Is there such thing as too much documentation?

**Comment by MrDinsdale** [comment]
This was touched upon in the last Toolkit Champions meeting.

I think the idea of automated documentation/style guide is no longer relevant with Blackjack Guides however the way in which we handle inline documentation in the Scss is still something that should be addressed.

In my opinion, inline comments should be used to highlight anything that might be seen as unusual. This might be a *hack* for browser compatibility perhaps which might not be immediately obvious to someone reading or functions/loops/mixins to explain exactly what is going on.

I think we should assume a certain level of CSS familiarity for people reading through the raw code too. Currently we have far too much inline documentation IMO, such as this from `c-btn`:

```
 * 1.  Allows styling of box model properties.
 * 2.  Reset browser styles.
 * 3.  Subtract border-width from the padding so buttons don't grow if the
 *     border-width is modified.
 * 4.  Tidy aligment for when the button size needs to be modified.
 * 5.  Make buttons inherit font styles (necessary when styling `input`s as
 *     buttons).
 * 6.  Set default button font-size.
 * 7.  Set default button font-weight.
 * 8.  Set default button text-alignment.
 * 9.  Remove anchor text-decoration (necessary when styling `a`s as buttons).
 * 10. Base transparent border for modifers to alter.
 * 11. Set default button border-radius.
 * 12. Set default button transition (color, background-color and border-color)
 * 13. Force all button-styled elements to appear clickable.
 * 14. Remove browser outline styles.
```

The vast majority of this should be extremely self explanatory and I'm not sure it adds much value. Where as this inline documentation for the `c-tile` selected indicator is far more useful:

```
 * Arrow markers to signify panel relationship.
 *
 * 1. Positions the marker between tile and panel
 * 2. Need to take off an extra pixel here to allow for browser rendering/
 *    rounding quirks.
 * 3. Rotate 45deg to allow it to mask the panel gradient and look like a
 *    notch in the panel (webkit placed after to prevent render quirk)
 * 4. Box-shadow that matches the panel background color to smooth the
 *    shadow transition
 * 5. Inset box-shadow that is offset to be visible only on the top edges
```

**Comment by joebell93** [comment]
Agree with everything that's been said here, I think it's only worth inline commenting things that are unique/require explanation - we shouldn't be documenting what standard CSS does

Going to suggest we add this to our CONTRIBUTING guidelines/CSS Style Guide

cc @aaronthomas @MrDinsdale

**Comment by joebell93** [comment]
p.s. sorry for the one-year-late response
