### ISSUE TITLE
Page Gradient Change

### ISSUE THREAD

**Issue by StefanMcCready** [sky-uk/toolkit#451]
**Is your feature request related to a problem? Please describe.**
Design have made an initial request for a change to the gradient shown on the background of every page.

We are looking to reduce the strength of the grey by 50% to make it closer to what it looks like on mobile.

**Describe the solution you'd like**
This will require a change to the `page` gradient within `settings/gradients`;

**Describe alternatives you've considered**
Going all out and getting rid of the gradient altogether. But thats not happening for a bit.

**Comment by mikejgregory** [comment]
So for now we have a step change to reduce the intensity of the gradient background. HEX values below.  The future goal is to remove the grad all together, this will create a cleaner appearance and open up opportunities to use more subtle gradients throughout.

**Comment by StefanMcCready** [comment]
Work complete.
