### ISSUE TITLE
Add further documentation to the Wiki

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit#80]
- [x] Create a custom sidebar and structure for the Wiki.
- [ ] Introduction to the Toolkit and Style Guide.
- [x] Information on how to get started with the Toolkit.
- [x] The purpose of `toolkit-core`, uses and its structure.
- [x] The purpose of `toolkit-ui`, uses and its structure.
- [ ] Individual `toolkit-ui` component documentation.
- [ ] How to integrating / modifying Toolkit styles.
- [x] Contributing (maybe just link back to [CONTRIBUTING.md](https://github.com/sky-uk/toolkit/blob/master/CONTRIBUTING.md))
- [ ] Building and deploying the Style Guide
- [ ] FAQ 
- [x] Archive of e-mail newsletters

**Comment by jackturnbull** [comment]
Related: https://github.com/sky-uk/toolkit/issues/102 (just seen this after raising previous one - feel free to close the one linked.)
