### ISSUE TITLE
How will we manage deprecation in post v1.0?

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit#96]
At the moment we’re a bit more lenient when it comes to breaking changes (because we’re `0.x`).

What would be the best way going forwards to warn people about upcoming breakages and deprecate gracefully (without `sass-deprecate`)?

**Comment by joebell93** [comment]
At the moment we’re a bit more lenient when it comes to breaking changes (because we’re `0.x`).

What would be the best way going forwards to warn people about upcoming breakages and deprecate gracefully (without `sass-deprecate`)?

**Comment by MrDinsdale** [comment]
Once we hit v1.0 and have semantic versioning in place this will be much easier.

Major releases should be relatively infrequent and any potentially breaking changes should be handled gracefully. Once we hit this point tools like `sass-deprecate` will most likely work much better however I personally think that good documentation and release notes will be the best way to handle this.

Ember have in-depth release notes which covers changes and how to update etc [release notes](http://emberjs.com/blog/2016/07/25/ember-2-7-and-2-8-beta-released.html) which is particularly useful. We could back this up with `@warn` deprecation messages although that could get frustrating as unlike JS for example we have no way to restrict them to only fire when a particular class is in use.
